- styx-cli/src/main/java/com/spotify/styx/cli/CliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/Main.java
- styx-cli/src/main/java/com/spotify/styx/cli/PlainCliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/PrettyCliOutput.java
- styx-cli/src/main/resources/logback.xml
- ~~make --component option to `ls` command a positional argument~~
- handle errors in single place
- remove header in output
- use System.{out,err} for output instead of logback
- longer timeout (90 seconds)
- specify api host with `-H` or env variable `STYX_CLI_HOST`
> cli overhaul

- styx-local-files-source/src/main/java/com/spotify/styx/LocalFileScheduleSource.java
This reduces latency for detecting changes, which also reduces the
run-time for the tests from about 50 seconds to 10 seconds (on Mac OSX).
> Increase local file watcher sensitivity

- styx-cli/src/main/java/com/spotify/styx/cli/CliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/Main.java
- styx-cli/src/main/java/com/spotify/styx/cli/PlainCliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/PrettyCliOutput.java
We keep breaking the CLI each time we add a new event, because of how we use Jackson.
This will make the cli more forgiving and fallback to just displaying the event name in case it can not parse it into the static types.
> [cli] Fallback to json inspection for unknown events

- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-common/src/main/java/com/spotify/styx/model/WorkflowState.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/InMemStorage.java
- styx-common/src/main/java/com/spotify/styx/util/WorkflowStateUtil.java
- styx-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
- styx-common/src/test/java/com/spotify/styx/util/WorkflowStateUtilTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SystemTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandlerTest.java
Fixes https://github.com/spotify/styx/issues/24
> Next natural trigger bug fix

- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/QueuedStateManagerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/SyncStateManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/DockerRunnerHandlerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandlerTest.java
> Limit Concurrency

- styx-common/src/main/java/com/spotify/styx/testdata/TestData.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodPollerTest.java
I might remove the isntanceStates() method on StateManager. I liked using instanceState directly, but we can derive it from the activeStates().
@rouz @jocke @fdema
> Add error event when pod is missing

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
Also lower the max backoff exponent to 4, which gives us a max retry time of 2^4*3m = 48m.
> Add setter for RetryUtil in scheduler builder

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/TriggerManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/TriggerManagerTest.java
check global enabled status before triggering all workflows, instead of
checking for each workflow.
this will also force ad-hoc triggering regardless of enabled or not.
> check global enabled status

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
For debugging purpose we might need to know on which host the workflow
instance is running. Host IP is included in pod status.
> Log workflow instance together with pod status

- styx-api-service/src/main/java/com/spotify/styx/api/BackfillResource.java
sequential execution is too slow for backfill with many partitions
> use parallelStream

- styx-cli/src/main/java/com/spotify/styx/cli/CliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/Main.java
- styx-cli/src/main/java/com/spotify/styx/cli/PlainCliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/PrettyCliOutput.java
It does go a bit wide if component and workflow names are long but it's much easier to get an overview.
> [CLI] Print backfills on one line each

- styx-api-service/src/main/java/com/spotify/styx/api/BackfillResource.java
- styx-common/src/main/java/com/spotify/styx/util/ReplayEvents.java
- styx-common/src/test/java/com/spotify/styx/util/ReplayEventsTest.java
instead of reading active instances per component which will result
a lot of datastore interactions, we read everything one time.
> read all active instances

- styx-common/src/main/java/com/spotify/styx/storage/AggregateStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/InMemStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/Storage.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
This is one of two proposed solutions for implementing throttling of the rate of creation of Docker containers from the scheduler.
The other path to be investigated aims at adding the throttler in the DockerOutputHandler instead.
> [WIP] Add RateLimiter in Scheduler

- pom.xml
this version includes netty 4.1.6.Final which fixed a memory leak. Similar issue has been reported here. https://github.com/grpc/grpc-java/issues/2358
Due to maven upper bound rule, a few transit dependencies have been bumped.
> upgrade bigtable-hbase-1.1

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesPodEventTranslator.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/LocalDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodResourceTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesPodEventTranslatorTest.java
This is a kludge to work around a Docker [exit code bug](https://github.com/kubernetes/kubernetes/issues/41516).
Now, when docker_termination_logging is set to "true" for the scheduled workflow at submission time, a message in the termination log will be expected for determination of the container exit status.
> Get container exit code reliably

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodResourceTest.java
The default Kubernetes termination message path: https://kubernetes.io/docs/tasks/debug-application-cluster/determine-reason-pod-failure/#setting-the-termination-log-file
> use the correct termination log file

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesPodEventTranslator.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesPodEventTranslatorTest.java
Consider a non-zero container exit code with a zero termination log exit code to be a failure.
> enhance exit code paranoia

- styx-api-service/src/test/java/com/spotify/styx/api/BackfillResourceTest.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
Once again bitten by datastore `.filter()` not adding to a list but overwriting with each call.
> Fix backfill filtering

- styx-cli/src/main/java/com/spotify/styx/cli/CliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/JsonCliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/Main.java
- styx-cli/src/main/java/com/spotify/styx/cli/PlainCliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/PrettyCliOutput.java
Add a `workflow show <component> <workflow>` command.
```
$ styx workflow show dano-test-pipeline dano-test
Component: dano-test-pipeline
Workflow: dano-test
Enabled: false
Schedule: DAYS
Commit: 79b49cdd161d3f17b43f005be22ead4095ca35c8
Image: registry.spotify.net/spotify/dano-test-pipeline:1490015757-d811bbe@sha256:c666cbfb44ac1debc3bb709a0268d19e3cd4e45a4d204dcbb4c3455b70c7dff7
Args: [bash, -c, echo hello digest world {}]
```
The output of the command is a `Workflow` with some fields from `WorkflowState` added / merged. Notably the `WorkflowState` takes precedence for the `Image` field value.
> styx cli: workflow show

- pom.xml
- styx-common/pom.xml
The uberjar contains native code for windows, linux and osx. Eliminates risk of build/run-time platform mismatch.
> use netty-tcnative-boringssl-static uberjar

- README.md
`@` cannot start a token in yaml. I.e. this example would have to be `schedule: '@hourly'`, which is an eyesore.
> readme: fix schedules example

- pom.xml
- styx-common/pom.xml
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/DockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/LocalDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/RoutingDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SystemTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/RoutingDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/SyncStateManager.java
Before starting the scheduler, poll for execution container state in order to record the completion of any containers that succeeded while styx was offline.
This avoids styx unnecessarily failing successfully completed executions due to having artifically "timed out" when starting up after downtime.
> eagerly restore container execution state

- pom.xml
- styx-cli/pom.xml
- styx-cli/src/main/java/com/spotify/styx/cli/CliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/CliUtil.java
- styx-cli/src/main/java/com/spotify/styx/cli/JsonCliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/Main.java
- styx-cli/src/main/java/com/spotify/styx/cli/PlainCliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/PrettyCliOutput.java
- styx-client/pom.xml
- styx-client/src/main/java/com/spotify/styx/client/ApiErrorException.java
- styx-client/src/main/java/com/spotify/styx/client/StyxApolloClient.java
- styx-client/src/main/java/com/spotify/styx/client/StyxBackfillClient.java
- styx-client/src/main/java/com/spotify/styx/client/StyxClient.java
- styx-client/src/main/java/com/spotify/styx/client/StyxClientFactory.java
- styx-client/src/main/java/com/spotify/styx/client/StyxResourceClient.java
- styx-client/src/main/java/com/spotify/styx/client/StyxSchedulerClient.java
- styx-client/src/main/java/com/spotify/styx/client/StyxStatusClient.java
- styx-client/src/main/java/com/spotify/styx/client/StyxWorkflowClient.java
- styx-common/src/main/java/com/spotify/styx/model/data/EventInfo.java
- styx-common/src/main/java/com/spotify/styx/util/EventUtil.java
- styx-schedule-source/pom.xml
The CLI would use the `styx-client` to perform the requests, also part of this PR.
**TODO**
- The CLI version is part of the requests' header; (removed)
_NOTE_
I am not sure about the way the client handles errors and exceptions at this point. The `throwable` we add to a failing `CompletionStage` is different in different cases but very obscure to users. 
I think we should extract at least two kind of checked exceptions: `ClientErrorException` and `ServerErrorException`. A more generic `IOException` can also be added to the signatures for unexpected arguments/payloads. In this way errors can be better documented and easier to handle.
However I am not sure what are the best practices for this case.
> Add styx-client module

- styx-scheduler-service/src/main/java/com/spotify/styx/ServiceAccountKeyManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
Also makes SA key secret checking and creation single threaded to avoid concurrent executions of workflows using the same service account from stepping on each others feet.
> validate & recreate SA keys if necessary

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/DockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/LocalDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/RoutingDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
Also remove default method, force all DockerRunner implementations to implement `cleanup()`.
> add cleanup method do routing docker runner

- pom.xml
- styx-scheduler-service/pom.xml
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManagerTest.java
Orphaned styx pods (e.g. due to https://github.com/spotify/styx/pull/185) currently causes SA secrets and keys from being removed when rotated.
Mitigate that by excluding terminated pods when enumerating actively used secrets.
> remove secrets used by terminated pods

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManagerTest.java
If only one key has been removed, ensure that the remaining key is not
left behind when new keys are created.
> remove lingering SA key when recreating

- styx-common/src/main/java/com/spotify/styx/util/Debug.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/DockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/LocalDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/RoutingDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/DockerRunnerHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodPollerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/RoutingDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/monitoring/MeteredProxyTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/DockerRunnerHandlerTest.java
When kube submissions time out (e.g. due to styx restart), the pod created by the submission will never be cleaned up.
This PR implements pod garbage collection by removing unwanted pods when polling.
> pod garbage collection

- README.md
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManagerTest.java
Even though styx will not delete keys used by running pods, containers might have started e.g. asynchronous dataflow jobs before exiting with exit code 0.
Deleting the keys used by these jobs will cause the jobs to fail.
A minimum key lifetime of 48 hours guarantees that such jobs starting just before the end of the 24h rotation epoch have at least 24h to finish before the key it uses is removed.
> extend SA key lifetime to 48 hours

- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/WorkflowResourceDecorator.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
The `WorkflowResourceDecorator` interface can be implemented to perform arbitrary modification of effective resource use by workflow instances at scheduler dequeue time.
This is effective regardless of trigger type.
> allow decoration of workflow resources

- README.md
- doc/design-overview.md
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/TerminationHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/TerminationHandlerTest.java
For certain use cases, an workflow instance execution would like to
return a well-known exit code (similar as 20 for missing dependency)
to Styx, and that would instruct Styx to stop retrying and fail the
execution immediately.
With something like 50 to mean "permanently failed, don't even retry",
by following this pattern:
https://github.com/spotify/luigi/blob/master/doc/configuration.rst#retcode
@ulzha PTAL
> fail fast upon receiving exit code 50

- styx-common/src/main/java/com/spotify/styx/util/ReplayEvents.java
As it turns out, when reading the backfill run state events, we _do_ expect to concurrently get new events after reading the active states.
> fix "unexpected newer event" spam

- styx-common/src/main/java/com/spotify/styx/util/GcpUtil.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManager.java
Current `styx e` cli output for an instance with wf SA permission problems is the raw json from the GoogleJsonResponseException message. That is not very user friendly.
With this change, the cli output will be something like:
```
Permission denied to service account: foo@barz.iam.google.com
```
Not sure if we should also add instructions here about granting e.g. `Key Admin` role on the wf SA for the Styx SA.
> log a nicer workflow SA permission denied message

- styx-scheduler-service/src/main/java/com/spotify/styx/BackfillTriggerManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandler.java
in most cases, this is due to workflow being removed or renamed by
users, so a warning feels better.
> warning instead of error

- styx-common/src/main/java/com/spotify/styx/util/ParameterUtil.java
- styx-common/src/test/java/com/spotify/styx/util/ParameterUtilTest.java
This is to fix #167
@danielnorberg
> be more strict than smart when parsing date time

- pom.xml
- styx-cli/pom.xml
- styx-cli/src/main/resources/logback.xml
- styx-cli/src/main/resources/simplelogger.properties
Turns out logback tries to look up the host name of the machine by making a DNS query. That is usually quick on machines in a datacenter but all too often fails (slowly) on workstations.
By replacing logback with slf4j-simple in the cli we can eliminate the above host name lookup and gain a 5s speedup 🎆 🍾 🍻 🎉 🎈 
**Before: ~5.5s startup**
```
$ time STYX_CLI_HOST=% styx e foo bar 2017-06-01 &>/dev/null
0.63s user 0.09s system 12% cpu 5.583 total
```
**After: ~0.5s startup**
```
$ time STYX_CLI_HOST=% java -Xnoclassgc -Xmx128m -Xms64m -Xverify:none -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -jar styx-cli/target/styx-cli.jar e foo bar 2017-06-01 &>/dev/null
0.52s user 0.06s system 126% cpu 0.460 total
```
Setting `STYX_CLI_HOST=%` ensures that we only measure time until …
> cli: fix slow startup

- styx-common/pom.xml
- styx-common/src/main/java/com/spotify/styx/util/ReplayEvents.java
- styx-common/src/test/java/com/spotify/styx/util/ReplayEventsTest.java
This "error" is expected and harmless while styx is up and getting api requests, so silence it. The `/status/activeStates` handler calls `replayActiveStates` with `printLogs=false`.
The error will still be logged during startup state restore replay, which is desirable it is not expected to happen then. `restoreState` calls `replayActiveStates` with `printLogs=true`.
These are the only two call sites.
> silence spam for /status/activeStates replay

- styx-common/src/main/java/com/spotify/styx/model/data/ExecStatus.java
- styx-common/src/main/java/com/spotify/styx/model/data/Execution.java
- styx-common/src/main/java/com/spotify/styx/model/data/WFIExecutionBuilder.java
- styx-common/src/test/java/com/spotify/styx/model/data/WFIExecutionBuilderTest.java
- styx-common/src/test/java/com/spotify/styx/model/data/WorkflowInstanceExecutionDataTest.java
- styx-common/src/test/java/com/spotify/styx/model/data/deprecated/WorkflowInstanceExecutionDataTest.java
- styx-common/src/test/java/com/spotify/styx/storage/BigTableStorageTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandler.java
Even if a `runError` or `halt` events are issued before the `submitted` event, hence before the execution id and/or docker image are made available, the `WorkflowInstanceExecutionData` now reports the failed `Execution` and shows the related error message (in case of runError) or the HALTED status.
> WFIExecutionData reports Execution even if failure happens before "submitted" event

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/DockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/DockerRunnerHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SystemTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodResourceTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManagerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesPodEventTranslatorTest.java
- commit sha
- docker image
- docker args
- service account
commit sha wasn't available in RunSpec so had to add it. Might be worthwhile to think about skipping the RunSpec and just pass the ExecutionDescription directly.
> Add some more env variables

- styx-client/pom.xml
- styx-client/src/main/java/com/spotify/styx/client/StyxApolloClient.java
- styx-client/src/main/java/com/spotify/styx/client/auth/GoogleIdTokenAuth.java
With this, `styx` CLI tool will require a logged in gcloud user or an activated service account.
Edit: no - if the credential is not found then CLI will attempt to call API without authentication as previously.
> cli: add Google ID token authentication

- styx-api-service/src/main/java/com/spotify/styx/StyxApi.java
- styx-api-service/src/main/java/com/spotify/styx/api/BackfillResource.java
- styx-api-service/src/main/java/com/spotify/styx/api/ResourceResource.java
- styx-api-service/src/main/java/com/spotify/styx/api/SchedulerProxyResource.java
- styx-api-service/src/main/java/com/spotify/styx/api/StatusResource.java
- styx-api-service/src/main/java/com/spotify/styx/api/StyxConfigResource.java
- styx-api-service/src/main/java/com/spotify/styx/api/WorkflowResource.java
- styx-client/src/main/java/com/spotify/styx/client/StyxApolloClient.java
- styx-common/src/main/java/com/spotify/styx/api/Api.java
- styx-common/src/main/java/com/spotify/styx/api/Middlewares.java
- styx-common/src/test/java/com/spotify/styx/api/MiddlewaresTest.java
Keep backward compatibility for older api versions while attaching
authValidator middleware to V3.
> Enable V3 api

- styx-api-service/src/test/java/com/spotify/styx/api/BackfillResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/SchedulerProxyResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/deprecated/BackfillResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/deprecated/CliResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/deprecated/WorkflowResourceTest.java
8080 is too well-known not to collide with others.
@axelri
> choose a more random port

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManagerTest.java
GCP Service Accounts have a low limit of number of keys. Having the rotation epoch greater than the timeout of "running" state (24 hours) means there is no chance of having three epochs of keys active at the same time. This means no more warnings about number of keys being too high.
> Increase key rotation epoch to weekly

- styx-common/src/main/java/com/spotify/styx/util/GcpUtil.java
- styx-common/src/test/java/com/spotify/styx/util/GcpUtilTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManagerTest.java
This kind of exception isn't handled properly hence if it happens users will see Google related exception as event description, which is not so friendly.
> Handle max number of keys created nicer

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
Reverts spotify/styx#221
Log persisting for debug level is not yet set up. I was unaware that the PR was not ready to merge.
> Revert "log k8s events at debug level"

- doc/api.apib
component level state PATCH only exists for V2 and lower, will be
deprecated soon.
@axelri PTAL
After being merged, we will generate html version to gh-pages branch.
> V3 api description

- checkstyle.xml
"optional" flag was added in 6.15 (we use 6.11.2)
> fix checkstyle config warning

- styx-api-service/src/main/java/com/spotify/styx/api/WorkflowResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
Users should be able to create workflows without specifying a docker image.
> Remove docker image requirement

- styx-scheduler-service/src/main/java/com/spotify/styx/ServiceAccountKeyManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/ServiceAccountKeyManagerTest.java
It seems Google's IAM API is returning 403's even though the service account used to make the call has ServiceAccountKeyAdmin permission on the service account. Not sure if this is new but haven't seen this problem before.
> treat iam 403s as 404

- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/DockerRunnerHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/DockerRunnerHandlerTest.java
Avoid WFI's timing out waiting on submission rate limiting.
This can cause a long backlog of duplicate pod submissions to build up, produce a lot of duplicate executions and delayed executions.
> move rate limiting to scheduler

- styx-api-service/src/main/java/com/spotify/styx/StyxApi.java
- styx-api-service/src/main/java/com/spotify/styx/api/BackfillResource.java
- styx-api-service/src/main/java/com/spotify/styx/api/ResourceResource.java
- styx-api-service/src/main/java/com/spotify/styx/api/SchedulerProxyResource.java
- styx-api-service/src/main/java/com/spotify/styx/api/StatusResource.java
- styx-api-service/src/main/java/com/spotify/styx/api/StyxConfigResource.java
- styx-api-service/src/main/java/com/spotify/styx/api/WorkflowResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/BackfillResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/ResourceResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/SchedulerProxyResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/StatusResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/deprecated/WorkflowResourceTest.java
Deprecated Java classes are still there. We either remove them
completely or keep them there, but will address that in a different PR.
> remove v0-v2 API endpoints

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
Fix bug in positioning the cleanup within the state machine.
Also fix failing tests.
There are instances where the a workflowInstance's runState is still kept
in the stateManager even though the execution failed. For example, the runState is
removed from the stateManager only when the runState isTerminal (meaning, Done or Error),
whereas Failed and Terminated are not considered terminal states. In
the case of cleaning up pods, we want to clean the pods once a workflowInstance
enters one of all those 4 states (Failed/Terminated/Done/Error). Running cleanup(..) only
under the condition !runState.isPresent() prevented us to do so.
Now we try to cleanup the pod if runState isPresent or delete directly if the pod is not tracked by any runState. In `cleanup` we make sure deleting the pod that …
> Fix bug in delay of pod cleanup

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
We have observed cases that pod is not seen for running state. That
happens after poller has fetched a list of pods, then styx creates a
new pod, that pod transits into running and the state machine transits
into running as well. So we end up with having a running state but no
pod.
To fix this, first get a snapshot of running states and then fetch pod
list. If the state is running, the associated pod should be in the list;
while if the state is not running yet, we will not take any action.
We may just stop using watcher at all, but that has bigger impact.
> racing between poller and watcher

- styx-cli/src/main/java/com/spotify/styx/cli/Main.java
- styx-client/src/main/java/com/spotify/styx/client/ClientErrorException.java
- styx-client/src/main/java/com/spotify/styx/client/StyxApolloClient.java
Print `Connection failed: connect timed out: https://styx.spotify.net` instead of full exception stack traces like: 
```
java.io.IOException: Request Request{method=POST, url=https://styx.spotify.net/api/v3/scheduler/trigger, tag=Request{method=POST, url=https://styx.spotify.net/api/v3/scheduler/trigger, tag=null}} failed
at com.spotify.apollo.http.client.TransformingCallback.onFailure(TransformingCallback.java:57)
at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:185)
at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: …
```
> client: nicer connection error message

- doc/api.apib
- styx-api-service/src/main/java/com/spotify/styx/StyxApi.java
- styx-api-service/src/main/java/com/spotify/styx/api/WorkflowResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/api/SchedulerResource.java
- styx-scheduler-service/src/test/java/com/spotify/styx/api/SchedulerResourceTest.java
* This reverts PR #255 (3aac3da) and reintroduces workflow CRUD REST API endpoints.
* The Styx workflow storage is now the source of truth.
* Integrations with CD platform and ingestion from external truth sources can be performed directly using the workflow CRUD REST API endpoints.
* Unavailability of CD platforms and external truth sources does not affect the workflows that are stored by Styx itself.
> restore workflow crud api

- styx-api-service/src/main/java/com/spotify/styx/StyxApi.java
- styx-api-service/src/main/java/com/spotify/styx/api/WorkflowResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
scoped client would add another Authorization header and that makes
nginx sad.
@bergman PTAL
> scoped client cannot be used when nginx is in front of scheduler

- styx-common/src/main/java/com/spotify/styx/util/IsClosedException.java
- styx-common/src/test/java/com/spotify/styx/model/data/WFIExecutionBuilderTest.java
- styx-common/src/test/java/com/spotify/styx/serialization/PersistentEventTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StateInitializingTrigger.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/api/SchedulerResource.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/DockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/StateManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/DockerRunnerHandler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SystemTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/api/SchedulerResourceTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManagerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/QueuedStateManagerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/DockerRunnerHandlerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandlerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/PublisherHandlerTest.java
This allows to asynchronously consume the processed internal events. A possible application for this is to publish such events to third-party services by implementing the `EventInterceptor` interface.
EDIT: In the latest implementation the `EventInterceptor` interface has been removed in favour of the standard Java `Consumer` interface.
> Add support for consuming internal events asynchronously

- doc/api.apib
- styx-api-service/src/main/java/com/spotify/styx/api/BackfillResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/BackfillResourceTest.java
- styx-cli/src/main/java/com/spotify/styx/cli/CliMain.java
- styx-client/src/main/java/com/spotify/styx/client/StyxApolloClient.java
- styx-client/src/main/java/com/spotify/styx/client/StyxBackfillClient.java
Also make use of the "status" query parameter in `backfillEditConcurrency` in the Styx client, to improve performance.
> Add ?status query parameter for GET backfill

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
With the current implementation of keeping the Pods around for some time after the Styx executions finish, we have an even stronger decoupling between the states in Styx and the Pods in the Kubernetes cluster. Receiving a Pod event that is not relevant for the current states within Styx is expected by design, making the related logging not belonging to the `warn` level.
Logging setup reference: https://github.com/spotify/styx/blob/master/CONTRIBUTING.md
> Change LOG level for Pod events

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerTest.java
- styx-standalone-service/src/main/resources/styx-standalone.conf
*Note*: This makes the gke `namespace` a required configuration parameter. The scheduler will not start without it.
> scheduler: configurable k8s namespace

- styx-cli/src/main/java/com/spotify/styx/cli/CliMain.java
- styx-cli/src/test/java/com/spotify/styx/cli/CliMainTest.java
- styx-client/src/main/java/com/spotify/styx/client/ApiErrorException.java
- styx-client/src/main/java/com/spotify/styx/client/StyxApolloClient.java
- styx-client/src/main/java/com/spotify/styx/client/auth/GoogleIdTokenAuth.java
- styx-client/src/test/java/com/spotify/styx/client/StyxApolloClientTest.java
Display a helpful error message telling the user how to set up credentials when getting a `401 Unauthorized` from Styx and there are no credentials available:
```
API error: Unauthorized: Please set up Application Default Credentials or set the GOOGLE_APPLICATION_CREDENTIALS env var to point to a file defining the credentials.
Hint: Try setting up credentials using gcloud: 
$ gcloud auth application-default login
```
> helpful credentials error message

- styx-common/src/main/java/com/spotify/styx/testdata/TestData.java
- styx-scheduler-service/src/main/java/com/spotify/styx/api/SchedulerResource.java
- styx-scheduler-service/src/main/java/com/spotify/styx/workflow/WorkflowInitializationException.java
- styx-scheduler-service/src/main/java/com/spotify/styx/workflow/WorkflowInitializer.java
- styx-scheduler-service/src/test/java/com/spotify/styx/api/SchedulerResourceTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/workflow/WorkflowInitializerTest.java
initializing next natural trigger could throw RuntimeException due to
wrong syntax of offset or schedule.
@ulzha PTAL
> validate workflow before storing and update

- styx-cli/src/main/java/com/spotify/styx/cli/PrettyCliOutput.java
#323 made the execution id disappear when replaying the events for workflow instances in QUEUED or PREPARED state, so in those cases the execution id do not show up with the CLI command `styx ls`. However, such information is not very relevant for the users and the execution id can still be retrieved via `styx events ...` so we can remove it completely from `styx ls`.
EDIT: we can also keep displaying the execution id for current executions
> Remove last execution id from 'styx ls'

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
In a high volume k8s cluster, resource versions go stale quickly enough that watching from a resource version returned by a pod list operation often fails with a "too old resource version" error.
Omitting the resource version parameter from the watch call causes k8s to watch from the latest resource version. This has been tested empirically using our GKE clusters but the docs are ambiguous on this point.
Styx might miss events when the watcher is re-established, but that is already the case.
In the high-volume case it does not seem likely that there is a way to not miss events using only the watcher, thus polling acts as a fallback.
For the low-volume case we could keep storing the last observed resource version etc in an attempt to not miss any events. However, I did not think that …
> k8s: watch from latest

- pom.xml
- styx-common/src/main/java/com/spotify/styx/util/ParameterUtil.java
- styx-common/src/main/java/com/spotify/styx/util/TimeUtil.java
- styx-common/src/test/java/com/spotify/styx/util/ParameterUtilTest.java
- styx-common/src/test/java/com/spotify/styx/util/TimeUtilTest.java
Basically to get this fix in: https://github.com/jmrozanec/cron-utils/issues/144
Due to a change introduced by
https://github.com/jmrozanec/cron-utils/issues/155, we throw exception
if get an empty optional. This doesn't change the orignal behavior at
all, and we don't exepct this thing to happen in our use cases.
This change https://github.com/jmrozanec/cron-utils/issues/200 breaks
our previous assumption, and that's why there are so many fixes in this PR.
> upgrade cron-utils

- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
There's no way to store the property as a [`Text`](https://cloud.google.com/appengine/docs/standard/java/javadoc/com/google/appengine/api/datastore/Text) object per se. But it seems that Text is just a wrapper around unindexed strings, so this should accomplish the same thing.
> Make workflow json be stored as long unindexed text

- styx-client/src/test/java/com/spotify/styx/client/StyxApolloClientTest.java
Let's not do real auth for unit test.
Apart from this, our code doesn't handle GCE default SA properly.
https://github.com/spotify/styx/blob/4c21ca1d6ae5894e15103e339c36b4a8f6b40c30/styx-client/src/main/java/com/spotify/styx/client/auth/GoogleIdTokenAuth.java#L61
For GCE default SA, this will return null, and we treat it as user
account!!
Those test cases failed in GCP Jenkins.
> use mock GoogleIdTokenAuth

- styx-scheduler-service/src/main/java/com/spotify/styx/api/SchedulerResource.java
- styx-scheduler-service/src/test/java/com/spotify/styx/api/SchedulerResourceTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/SyncStateManager.java
The `SyncStateManager` used in some tests might not behave exactly as the `QueuedStateManager` used online. This makes parts of the tests relying on `SyncStateManager` potentially wrong or irrelevant. 
In this specific case, different error handling in `SyncStateManager` with respect to `QueuedStateManager` caused unexpected API error codes being returned from the event injecting APIs.
In future PRs we could remove `SyncStateManager` from these tests and think about a different approach.
> Improve error handling for events injection APIs

- styx-cli/src/main/java/com/spotify/styx/cli/CliMain.java
Before:
```
$ styx workflow delete foo bar
Sure you want to delete the workflow bar in component foo? [yN] n
com.spotify.styx.cli.CliExitException
at com.spotify.styx.cli.CliExitException.of(CliExitException.java:52)
at com.spotify.styx.cli.CliMain.workflowDelete(CliMain.java:321)
at com.spotify.styx.cli.CliMain.run(CliMain.java:256)
at com.spotify.styx.cli.CliMain.run(CliMain.java:166)
at com.spotify.styx.cli.CliMain.run(CliMain.java:123)
at com.spotify.styx.cli.CliMain.main(CliMain.java:116)
```
After:
```
$ styx workflow delete foo bar
Sure you want to delete the workflow bar in component foo? [yN] n
```
> propagate CliExitException to main

- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
We suspect there is a race condition between when `currentResourceUsage` is calculated (by assuming workflows in `State.NEW` consume resources) and the thread of `TriggerManager` creating workflows with `State.NEW`. `QueuedStateManager` then takes a little while till it transitions those to `State.QUEUED`. This we think causes sometimes inconsistent metrics on resource usage.
> Resource usage count fix

- styx-scheduler-service/src/main/java/com/spotify/styx/InMemWorkflowCache.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
The logging regarding the workflowCache is updated and changed to DEBUG level. The reasoning for that is to only track, at the INFO level, the occurrence of a workflow correctly added/modified/removed, including (implicitly) all the related operations: storage update, cache update, consumers being called, metrics being registered, etc. 
Correct cache operations are a lower level implementation whose correct functioning can be tracked at the DEBUG level (optionally).
> Update logging for Workflows added/modified/removed

- styx-common/src/main/java/com/spotify/styx/model/ExecutionDescription.java
Our ObjectMapper is already configured to use snake case.
> remove redundant @JsonProperty annotations

- styx-scheduler-service/src/main/java/com/spotify/styx/ServiceAccountKeyManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/ServiceAccountKeyManagerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManagerTest.java
The main purpose of this PR is to make the SA management in Styx compatible with a distributed multi-master setup. Failures when creating a new secret due to racy conditions among schedulers will be handled as non-erroneous behaviour; related GCP keys created during the failing attempt are going to be cleaned-up (as a best effort attempt).
> Cleanup GCP keys if related secret's creation fails with 409

- styx-cli/src/main/java/com/spotify/styx/cli/CliMain.java
- styx-cli/src/test/java/com/spotify/styx/cli/CliMainTest.java
- styx-client/src/main/java/com/spotify/styx/client/StyxApolloClient.java
- styx-client/src/main/java/com/spotify/styx/client/StyxWorkflowClient.java
- styx-client/src/test/java/com/spotify/styx/client/StyxApolloClientTest.java
the client side is more generic with the ability to handle a complete
workflow state including `enabled`, `nextNaturalTrigger`, and
`nextNaturalOffsetTrigger`.
_Github has signed me out due to long time idling so I decided to write some code._
> add CLI support to enable and disable workflows

- styx-cli/src/main/java/com/spotify/styx/cli/CliMain.java
- styx-cli/src/main/java/com/spotify/styx/cli/CliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/JsonCliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/PlainCliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/PrettyCliOutput.java
- styx-cli/src/test/java/com/spotify/styx/cli/CliMainTest.java
- styx-cli/src/test/java/com/spotify/styx/cli/JsonCliOutputTest.java
- styx-cli/src/test/java/com/spotify/styx/cli/PlainCliOutputTest.java
- styx-cli/src/test/java/com/spotify/styx/cli/PrettyCliOutputTest.java
- styx-common/src/main/java/com/spotify/styx/api/BackfillsPayload.java
Made column sizes more appropriate when listing workflows using CLI, and also truncating backfill descriptions by default. To not truncate you supply the command "--no-trunc" similar to Docker, and then you will get the full descriptions.
> Improved CLI Readability

- styx-common/src/main/java/com/spotify/styx/model/StyxConfig.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/WorkflowExecutionGate.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
Add a `WorkflowExecutionGate` scheduler plugin interface that can be used to implement blocking of workflow executions e.g. due to missing dependencies or other unfulfilled preconditions.
> check for dependencies before executing wf

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
Allow looking up WFIs for pods spotted in the container engine visualizer (which only shows pod UIDs).
> log pod UID

- styx-cli/src/main/java/com/spotify/styx/cli/PlainCliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/PrettyCliOutput.java
- styx-cli/src/test/java/com/spotify/styx/cli/PrettyCliOutputTest.java
- styx-common/src/main/java/com/spotify/styx/state/RunState.java
- styx-common/src/main/java/com/spotify/styx/state/StateData.java
- styx-common/src/test/java/com/spotify/styx/state/RunStateTest.java
- styx-common/src/test/java/com/spotify/styx/state/StateDataTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
We're always only using the last message anyway.
As opposed to https://github.com/spotify/styx/pull/369 this should be backwards compatible.
> single (last) message in RunState

- styx-common/src/main/java/com/spotify/styx/util/Time.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/MetricsStats.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/MonitoringHandler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/NoopStats.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/Stats.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/monitoring/MetricsStatsTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/MonitoringHandlerTest.java
Make this measurement less dependent on event transitions happening on the same scheduler instance in preparation for HA multiple instance scheduler setup.
> move submission -> running timing to k8s runner

- styx-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
This PR also fixes test failures on JDK9 due to the differences applied to `java.time.Clock.systemUTC()` (ref. https://bugs.openjdk.java.net/browse/JDK-8068730)
> Use fixed timestamp for tests

- styx-cli/src/main/java/com/spotify/styx/cli/JsonCliOutput.java
- styx-cli/src/test/java/com/spotify/styx/cli/JsonCliOutputTest.java
It's a bit weird to emit a json object with `WorkflowId.toString()` as keys.
Before: 
```
$ styx --json ls
{
"WorkflowId{componentId=foo-component, id=foo-workflow}": [ ... ],
"WorkflowId{componentId=bar-component, id=bar-workflow}": [ ... ],
...
}
```
After: 
```
$ styx --json ls
{
"foo-component#foo-workflow": [ ... ],
"bar-component#bar-workflow": [ ... ],
...
}
```
> nicer --json ls keys

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesPodEventTranslator.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodPollerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesPodEventTranslatorTest.java
The container engine visualizer shows the container name when hovering.
Using the execution id as the container name makes it a little easier to look up the corresponding execution/wfi for an container spotted in the visualizer.
> name the containers

- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/MetricsStats.java
- styx-scheduler-service/src/test/java/com/spotify/styx/monitoring/MetricsStatsTest.java
After #385, retrieving active states requires a call to persistent layer with considerable higher latencies. In case of high number of registered workflows, `registerActiveStatesMetric` per each workflow could cause the metric framework to be very slow.
> Hot-fix disable activeStatesMetric per Workflow

- styx-common/src/main/java/com/spotify/styx/util/WorkflowValidator.java
We're bound by Datastore property size limit really, https://cloud.google.com/datastore/docs/concepts/limits . Command lines usually can be 2MB long. It just astonishes users if knocked down by orders of magnitude.
> Bump MAX_DOCKER_ARGS_TOTAL

- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
We've observed timeouts being applied potentially too late on a workflow state - when the state has already transitioned forward, so we see the timeout out of order in the events sequence. This PR logs which state the timeout has been applied to. We may in the future want to increase the timeout limit for some states.
> Log type of state that times out

- styx-scheduler-service/src/main/java/com/spotify/styx/BackfillTriggerManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/TriggerManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/BackfillTriggerManagerTest.java
When triggering one backfill fails, continue triggering others. `InterruptedException` is not handled specially any more because when that happens executor thread is stopping.
> guarded backfill triggering

- styx-api-service/src/test/java/com/spotify/styx/api/BackfillResourceTest.java
- styx-common/src/main/java/com/spotify/styx/model/EventVisitor.java
- styx-common/src/main/java/com/spotify/styx/model/data/WFIExecutionBuilder.java
- styx-common/src/main/java/com/spotify/styx/serialization/PersistentEvent.java
- styx-common/src/main/java/com/spotify/styx/state/RunState.java
- styx-common/src/main/java/com/spotify/styx/state/StateData.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-common/src/main/java/com/spotify/styx/testdata/TestData.java
- styx-common/src/main/java/com/spotify/styx/util/EventUtil.java
- styx-common/src/test/java/com/spotify/styx/WorkflowInstanceEventFactory.java
- styx-common/src/test/java/com/spotify/styx/model/data/WFIExecutionBuilderTest.java
- styx-common/src/test/java/com/spotify/styx/serialization/PersistentEventTest.java
- styx-common/src/test/java/com/spotify/styx/state/RunStateTest.java
- styx-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
- styx-common/src/test/java/com/spotify/styx/util/ReplayEventsTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/api/SchedulerResourceTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/QueuedStateManagerTest.java
Needed for upcoming use of ShardedCounters (https://github.com/spotify/styx/pull/378) - so that we can consistently decrement the right resources (that were incremented upon dequeue), when the execution finishes.
>  Add resourceIds in StateData to propagate and persist them

- styx-api-service/src/main/java/com/spotify/styx/StyxApi.java
- styx-api-service/src/main/java/com/spotify/styx/api/ResourceResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/BackfillResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/ResourceResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-common/src/main/java/com/spotify/styx/storage/AggregateStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorageTransaction.java
- styx-common/src/main/java/com/spotify/styx/storage/InMemStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/Storage.java
- styx-common/src/main/java/com/spotify/styx/storage/StorageTransaction.java
- styx-common/src/main/java/com/spotify/styx/util/Shard.java
- styx-common/src/main/java/com/spotify/styx/util/ShardedCounter.java
- styx-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
- styx-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTransactionTest.java
- styx-common/src/test/java/com/spotify/styx/util/ShardedCounterTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/QueuedStateManagerTest.java
Refactor `ShardedCounter` to depend on `Storage` and `StorageTransaction` instead of `Datastore`.
As per the current setup of how Styx communicates with Datastore, there are two places where read/write logic happens, in `DatastoreStorage` used by `AggregateStorage implements Storage` and `DatastoreStorageTransaction implements StorageTransaction`, so it was a bit confusing when deciding where to put the logic needed for `ShardedCounter`.  My approach was to put as much as I could in `DatastoreStorageTransaction` (whatever was required to be done in a transaction) and the rest in `DatastoreStorage`.
> Shardedcounter refactoring

- styx-scheduler-service/src/main/java/com/spotify/styx/BackfillTriggerManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/BackfillTriggerManagerTest.java
It is possible (maybe it shouldn't) to create backfills that have start=end, for which `allTriggered` will never be reached. Complements #402 
@honnix @ulzha PTAL
> Mark completed backfills as allTriggered

- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
This prevents starvation when dequeuing workflow instances.
> Sort by time when scheduling

- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
Reading active states consumes a big part of scheduler tick, so little
time is used for actual execution. By keeping the loop flowing we can
get better throughput without having a big burst.
> flow the execution

- styx-common/src/main/java/com/spotify/styx/storage/InMemStorage.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/StaleEventException.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/StateManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/QueuedStateManagerTest.java
This is a early prototype of an idea to improve slow event processing and spot stale events that were enqueued but should not be processed anymore.
We can either supply the expected counter explicitly according to custom logic (for example according to the current state of active states read at the beginning of a tick) or, as a default behaviour, just read the current counter from Datastore at the moment of enqueueing (no transactions involved).
> Strict counter verification in event processing

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManager.java
So that it is easier to know who.
@NatashaL PTAL
> print workflow id when failed to create keys

- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/MeteredProxy.java
- styx-scheduler-service/src/test/java/com/spotify/styx/monitoring/MeteredProxyTest.java
This kind of exception we would prefer not to get alert. With a specific type we can then filter out.
> to report invalid execution exception

- styx-scheduler-service/src/test/java/com/spotify/styx/SystemTest.java
As we discussed, we will temporarily identify and disable them, and work on a branch (https://github.com/spotify/styx/tree/deflaky-tests) to get them fixed.
> disable known flaky tests

- styx-common/src/main/java/com/spotify/styx/model/StyxConfig.java
- styx-common/src/main/java/com/spotify/styx/storage/AggregateStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorageTransaction.java
- styx-common/src/main/java/com/spotify/styx/storage/InMemStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/Storage.java
- styx-common/src/main/java/com/spotify/styx/util/StreamUtil.java
- styx-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
Active workflow instances are indexed using 128 entity groups (index shards).
The id's of the instances are stored as the names of child entities in the index shards. The entities themselves are empty.
This avoids the 1MB max entity size limit that might be hit if instance id's are stored as list properties.
> strongly consistent wfi listing using shards

- pom.xml
Attempt to mitigate circleci timeouts due to trying to download non-jitpack artifacts from jitpack instead of maven central.
Avoid these annoying failures: https://circleci.com/gh/spotify/styx/3853
> prefer maven central - avoid jitpack timeouts

- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/DockerRunnerHandler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/DockerRunnerHandlerTest.java
All currently active WFIs have execution id assigned in PREPARE by the `ExecutionDescriptionHandler`.
> remove old execution id migration code

- README.md
It turned out we never mentioned how to set up API and Scheduler
separately. It's pretty much impossible to describe HA in more details
unless we open up a whole doc talking about thow to set up for different
scenarios than standalone.
> briefly talk about HA in readme

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/TriggerManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/TriggerManagerTest.java
This is on critical path and trigger is usually very slow due to
datastore operation.
@danielnorberg Let's talk about this.
> Do not use common FJP

- styx-scheduler-service/src/main/java/com/spotify/styx/api/SchedulerResource.java
- styx-scheduler-service/src/test/java/com/spotify/styx/api/SchedulerResourceTest.java
When users call `styx trigger` on an already running partition, they only saw `API error: 500 Internal Server Error`, which was wrong and lacking more information. This corrects the return code to 409 instead, and adds the exception stack trace in cases of status code 500.
> Check for correct exception type when triggering already triggered instances 

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesPodEventTranslator.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodPollerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodResourceTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesPodEventTranslatorTest.java
Start a sidecar container that runs forever in order to keep the pod alive after the main container exits. Styx can then reap the pod whenever it wishes, without missing the exit code and termination log
due to aggressive k8s pod GC.
> use a keepalive sidecar container

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
Without this, we get the default (non-zero in GKE) resource allocation.
> request no resources for keepalive container

- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
It would be useful to be able to scrape logs only for events that did not get discarded due to being stale etc.
> state manager: log verified events

- styx-common/src/main/java/com/spotify/styx/model/WorkflowId.java
- styx-common/src/main/java/com/spotify/styx/model/WorkflowInstance.java
- styx-common/src/main/java/com/spotify/styx/state/RunState.java
- styx-common/src/test/java/com/spotify/styx/model/WorkflowInstanceTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/TriggerManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/DockerRunnerHandler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/TransitionLogger.java
It would be useful to get all log messages for a WFI by searching for a single string, the wfi key, instead of having to search both for the key and the `WorkflowInstance{workflowId=...}` string. And the key is a lot easier to handle.
> consistently log the wfi key - ease log analysis

- styx-cli/src/main/java/com/spotify/styx/cli/CliMain.java
- styx-cli/src/test/java/com/spotify/styx/cli/CliMainTest.java
- styx-client/src/main/java/com/spotify/styx/client/StyxApolloClient.java
Make the cli print the message of any encountered `ClientErrorException` and its root cause.
On unknown host, e.g. due to `STYX_CLI_HOST` typo:
```
Client error: Request failed: GET http://syx.spotify.net/api/v3/status/activeStates: UnknownHostException: syx.spotify.net: nodename nor servname provided, or not known
```
On connection failure due to e.g. network problem:
```
Client error: Request failed: GET http://styx.foo.net:4711/api/v3/status/activeStates: ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:4711
```
On http protocol error, e.g. talking to something unexpected:
```
Client error: Request failed: GET http://styx.foo.net:4711/api/v3/status/activeStates: ProtocolException: Unexpected status line: deadbeef
```
The `--debug` flag causes the full stack traces to be …
> cli: print client error cause & add --debug flag

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
We want to keep the pod around until the WFI has transitioned out of
RUNNING so we can get the exit code and not falsely label executions as
having failed just because the pod "expired" before the RunState managed
to transition (e.g. due to datastore contention and slowness).
> do not delete pods if the WFI is still RUNNING

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesPodEventTranslator.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesPodEventTranslatorTest.java
Emit runError on NodeLost instead of just waiting for the pod to disappear and then getting a "No pod associated with this instance" error.
Kubernetes sets this reason on pods that are being deleted because the node is unresponsive.
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/util/node/controller_utils.go?utf8=%E2%9C%93#L55
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/util/node/controller_utils.go?utf8=%E2%9C%93#L117
> handle NodeLost

- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-common/src/main/java/com/spotify/styx/util/CachedSupplier.java
- styx-scheduler-service/src/main/java/com/spotify/styx/ServiceAccountKeyManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/TriggerManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandler.java
Went looking for any occurrences where an exception cause is swallowed (caught and then neither logged nor rethrown), a bit like this:
$ git grep -A 5 "} catch" | grep -v ", e)" | grep -C 2 -iP "log\."
> Always capture exception causes

- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
Let's log this exception as well. There's nothing else logging it upstream when hit by a user request.
@ulzha ptal
> log workflow read exception

- styx-api-service/src/main/java/com/spotify/styx/api/BackfillResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/BackfillResourceTest.java
- styx-cli/src/main/java/com/spotify/styx/cli/CliMain.java
- styx-cli/src/test/java/com/spotify/styx/cli/CliMainTest.java
- styx-cli/src/test/java/com/spotify/styx/cli/JsonCliOutputTest.java
- styx-client/src/main/java/com/spotify/styx/client/StyxApolloClient.java
- styx-client/src/main/java/com/spotify/styx/client/StyxBackfillClient.java
- styx-client/src/test/java/com/spotify/styx/client/StyxApolloClientTest.java
- styx-common/src/main/java/com/spotify/styx/model/Backfill.java
- styx-common/src/main/java/com/spotify/styx/model/BackfillInput.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorageTransaction.java
- styx-common/src/main/java/com/spotify/styx/util/ParameterUtil.java
- styx-common/src/main/java/com/spotify/styx/util/TimeUtil.java
- styx-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
- styx-common/src/test/java/com/spotify/styx/util/ParameterUtilTest.java
- styx-common/src/test/java/com/spotify/styx/util/TimeUtilTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/BackfillTriggerManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/BackfillTriggerManagerTest.java
minimum effort to make this feature. everything being the same, but to
trigger backfill in reversed order, user only needs to put `start` after
`end`, where `start` is inclusive and `end` is exclusive as it is today.
> trigger backfill in reversed order

- styx-api-service/src/main/java/com/spotify/styx/api/workflow/WorkflowInitializer.java
- styx-api-service/src/test/java/com/spotify/styx/api/workflow/WorkflowInitializerTest.java
Avoid potential corruption, inconsistencies or partial updates due to races, failures, restarts, etc.
> store workflow in transaction

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodResourceTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
Unique container naming causes logs to end up in separate stackdriver logs and breaks log exporting.
> revert container naming: use "styx-run"

- styx-api-service/src/main/java/com/spotify/styx/api/workflow/WorkflowInitializer.java
- styx-api-service/src/test/java/com/spotify/styx/api/workflow/WorkflowInitializerTest.java
Reverts spotify/styx#520
This doesn't work unfortunately. We cannot read workflow from transaction after `store` it so `updateNextNaturalTrigger` failed.
We got `com.spotify.styx.util.ResourceNotFoundException`.
@NatashaL PATL
> Revert "store workflow in transaction"

- styx-api-service/src/main/java/com/spotify/styx/StyxApi.java
- styx-common/pom.xml
- styx-common/src/main/java/com/spotify/styx/api/Api.java
- styx-common/src/main/java/com/spotify/styx/api/Middlewares.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-common/src/test/java/com/spotify/styx/api/MiddlewaresTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/BackfillTriggerManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Cleaner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/TriggerManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-standalone-service/src/main/java/com/spotify/styx/StyxService.java
add tracing to styx api/scheduler requests and internals
A next step after this PR is to instrument the storage methods etc with spans to get more granular breakdown of what's going on in there.
> tracing of requests & internals

- styx-common/src/main/java/com/spotify/styx/util/GuardedRunnable.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SystemTest.java
Current hard coded tick interval of ~1 hz is quite expensive for deployments with a lot of workflows due to causing a lot of datastore reads. This allows us to configure a more appropriate tick interval to lower datastore costs.
The default tick interval is unchanged.
Also add jitter to the tick scheduling to have less contention on datastore.
> configurable scheduler & trigger tick interval + jitter scheduling

- styx-common/src/main/java/com/spotify/styx/util/ShardedCounter.java
- styx-common/src/test/java/com/spotify/styx/util/ShardedCounterTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
An alternative to https://github.com/spotify/styx/pull/534.
By doing a best-effort resource limit check before dequeue, we can avoid exponential backoff delay and also avoid consuming the dequeue rate limit.
> scheduler: check resource limit before dequeue

- styx-api-service/src/test/java/com/spotify/styx/api/StatusResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-common/src/main/java/com/spotify/styx/model/Backfill.java
- styx-common/src/main/java/com/spotify/styx/model/EventVisitor.java
- styx-common/src/main/java/com/spotify/styx/model/data/Execution.java
- styx-common/src/main/java/com/spotify/styx/model/data/WFIExecutionBuilder.java
- styx-common/src/main/java/com/spotify/styx/serialization/PersistentEvent.java
- styx-common/src/main/java/com/spotify/styx/state/RunState.java
- styx-common/src/main/java/com/spotify/styx/state/StateData.java
- styx-common/src/main/java/com/spotify/styx/util/EventUtil.java
- styx-common/src/test/java/com/spotify/styx/WorkflowInstanceEventFactory.java
- styx-common/src/test/java/com/spotify/styx/model/data/WFIExecutionBuilderTest.java
- styx-common/src/test/java/com/spotify/styx/model/data/WorkflowInstanceExecutionDataTest.java
- styx-common/src/test/java/com/spotify/styx/serialization/PersistentEventTest.java
- styx-common/src/test/java/com/spotify/styx/state/RunStateTest.java
- styx-common/src/test/java/com/spotify/styx/storage/BigTableStorageTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
When getting workflow instances through the API, expose commit sha of execution, if available.
> Commit sha for executions

- styx-api-service/src/test/java/com/spotify/styx/api/StatusResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-common/src/main/java/com/spotify/styx/model/EventVisitor.java
- styx-common/src/main/java/com/spotify/styx/model/data/WFIExecutionBuilder.java
- styx-common/src/main/java/com/spotify/styx/serialization/PersistentEvent.java
- styx-common/src/main/java/com/spotify/styx/state/RunState.java
- styx-common/src/main/java/com/spotify/styx/util/EventUtil.java
- styx-common/src/test/java/com/spotify/styx/WorkflowInstanceEventFactory.java
- styx-common/src/test/java/com/spotify/styx/serialization/PersistentEventTest.java
- styx-common/src/test/java/com/spotify/styx/state/RunStateTest.java
- styx-common/src/test/java/com/spotify/styx/storage/BigTableStorageTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
There are no existing `created` records with `commitSha` and the event is no longer emitted.
> revert addition of `commitSha` to `created`

- styx-api-service/src/main/java/com/spotify/styx/StyxApi.java
- styx-api-service/src/main/java/com/spotify/styx/api/BackfillResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/BackfillResourceTest.java
- styx-common/src/main/java/com/spotify/styx/util/ReplayEvents.java
- styx-common/src/test/java/com/spotify/styx/util/ReplayEventsTest.java
- styx-test/pom.xml
* read active states by backfill trigger id
* skip replaying of running workflow instances
* parallel stream -> fork join pool
> Backfill status performance improvement

- styx-scheduler-service/src/main/java/com/spotify/styx/MessageUtil.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/MessageUtilTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/QueuedStateManagerTest.java
Use same message emission code in both `Scheduler` and
`QueuedStateManager` to ensure that duplicate messages are not emitted.
> refactor "Resource limit reached" message handling

- styx-api-service/src/main/java/com/spotify/styx/StyxApi.java
- styx-api-service/src/main/java/com/spotify/styx/api/BackfillResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/BackfillResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/VersionedApiTest.java
- styx-common/src/main/java/com/spotify/styx/storage/AggregateStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-common/src/main/java/com/spotify/styx/util/CloserUtil.java
- styx-common/src/test/java/com/spotify/styx/storage/AggregateStorageTest.java
- styx-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
- styx-common/src/test/java/com/spotify/styx/util/CloserUtilTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/TriggerManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/TriggerManagerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/QueuedStateManagerTest.java
Have a single well-tested method for shutting down executor services and use that instead of duplicating variations of the same shutdown logic everywhere.
One of the tests breaks code coverage on Java 8 so it is disabled there but it will be run by our Java 10+ CI pipeline.
> refactor fjp/executor shutdown

- styx-common/src/main/java/com/spotify/styx/util/GrpcContextUtil.java
- styx-common/src/test/java/com/spotify/styx/util/GrpcContextUtilTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesPodEventTranslator.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesPodEventTranslatorTest.java
* Make pod watcher asynchronous to avoid falling behind and getting disconnected.
* Let events for a pod coalesce in order to avoid re-processing for each small incremental pod update event.
* Process pod update event batches on the same thread as the poller, eliminate race conditions.
* Parallelize processing of pod update events to defeat IO latency.
> k8s: optimize watcher

- styx-common/src/main/java/com/spotify/styx/api/BackfillPayload.java
- styx-common/src/main/java/com/spotify/styx/api/BackfillsPayload.java
- styx-common/src/main/java/com/spotify/styx/api/EventsPayload.java
- styx-common/src/main/java/com/spotify/styx/api/ResourcesPayload.java
- styx-common/src/main/java/com/spotify/styx/api/RunStateDataPayload.java
- styx-common/src/main/java/com/spotify/styx/model/Backfill.java
- styx-common/src/main/java/com/spotify/styx/model/BackfillInput.java
- styx-common/src/main/java/com/spotify/styx/model/EditableBackfillInput.java
- styx-common/src/main/java/com/spotify/styx/model/ExecutionDescription.java
- styx-common/src/main/java/com/spotify/styx/model/Resource.java
- styx-common/src/main/java/com/spotify/styx/model/TriggerRequest.java
- styx-common/src/main/java/com/spotify/styx/model/Workflow.java
- styx-common/src/main/java/com/spotify/styx/model/WorkflowConfiguration.java
- styx-common/src/main/java/com/spotify/styx/model/WorkflowState.java
- styx-common/src/main/java/com/spotify/styx/serialization/Json.java
- styx-common/src/main/java/com/spotify/styx/state/Message.java
- styx-common/src/main/java/com/spotify/styx/state/StateData.java
- styx-common/src/test/java/com/spotify/styx/serialization/JsonTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesPodEventTranslator.java
Make the json parser ignore unknown properties when deserializing.
Allow forwards compatibility, e.g. cli should not fail to deserialize
json with new "unknown" properties from a newer server.
In practice this is already manually configured for most classes.
Instead, make it the default by configuring the mapper directly.
> json: ignore unknown properties when deserializing

- styx-cli/src/main/java/com/spotify/styx/cli/CliMain.java
- styx-cli/src/test/java/com/spotify/styx/cli/CliMainTest.java
Allow `styx t -e FOO=bar comp wf param` and `styx backfill create -e FOO=bar comp wf start end conc`
The `-e` argument swallowed all subsequent args that did not start with
`-`, including component, workflow id etc.
Now the `-e` argument will only take one subsequent `NAME=val` arg.
> cli: allow inline `-e NAME=val`

- doc/api.apib
- styx-api-service/src/main/java/com/spotify/styx/api/BackfillResource.java
- styx-api-service/src/main/java/com/spotify/styx/api/StatusResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/BackfillResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/StatusResourceTest.java
- styx-cli/src/main/java/com/spotify/styx/cli/PrettyCliOutput.java
- styx-cli/src/test/java/com/spotify/styx/cli/PrettyCliOutputTest.java
- styx-common/src/main/java/com/spotify/styx/api/RunStateDataPayload.java
- styx-common/src/main/java/com/spotify/styx/util/ReplayEvents.java
- styx-common/src/test/java/com/spotify/styx/util/GrpcContextUtilTest.java
- styx-common/src/test/java/com/spotify/styx/util/ReplayEventsTest.java
- styx-test/src/main/java/com/spotify/styx/util/ClassEnforcer.java
- styx-test/src/test/java/com/spotify/styx/util/ClassEnforcerTest.java
Include those timestamps so that for completed workflow instance the client will be able to tell when it started and when it finished.
Timestamps can be used to check how long it took for the workflow instance to complete.
> include initial and latest timestamps in RunStateData

- styx-common/src/main/java/com/spotify/styx/util/TimeUtil.java
- styx-common/src/test/java/com/spotify/styx/util/TimeUtilTest.java
`Instant#plus()` doesn't support `weeks`, `months`, `years`, etc. This fixes that by falling back to computing step by step.
Without needing to support those cases with a proper implementation of `plus` function, falling back seems good enough for those units in terms of performance.
> Fix unsupported unit

- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/DockerRunnerHandler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/HandlerUtil.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandlerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/HandlerUtilTest.java
Set parameter in execution description, instead of the `{}` placeholder.
This PR changes event content, so technically backward incompatible.
When users see an execution description in `styx events` etc, the `{}` part is confusing; they think they made an error by somehow failing to set a date.
> set parameter in ExecutionDescription

- styx-api-service/src/main/java/com/spotify/styx/api/WorkflowResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-common/src/main/java/com/spotify/styx/storage/BigtableStorage.java
- styx-common/src/test/java/com/spotify/styx/storage/BigTableStorageTest.java
Return 404 instead of 500 if no event found for workflow instance. This is change existing API behaviour. If users check HTTP code explicitly for their logic, that will stop working.
This is not a server error.
> throw more concrete exception

- styx-common/src/main/java/com/spotify/styx/util/ReplayEvents.java
- styx-common/src/test/java/com/spotify/styx/util/ReplayEventsTest.java
When searching and replaying events for backfill, ignore missing events and try to replay as much as possible.
In case of lost of event in Bigtable for whatever reason, replay should try as much as it can.
Unit test.
> best effort replay ignoring missing event

- styx-api-service/pom.xml
- styx-api-service/src/main/java/com/spotify/styx/api/SchedulerProxyResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/SchedulerProxyResourceTest.java
Apollo doesn't put query parameters back to url, so they all get lost.
To address https://github.com/spotify/styx/pull/607#issuecomment-431038204
Unit test
> add query parameters to url

- styx-common/src/main/java/com/spotify/styx/model/StyxConfig.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SystemTest.java
remove old unnecessary / unused counter init code
It is unnecessary and a little unsettling to mutate all the counter limits on startup.
> remove old unnecessary / unused counter init code

- styx-api-service/src/main/java/com/spotify/styx/api/ResourceResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/ResourceResourceTest.java
- styx-common/src/main/java/com/spotify/styx/storage/AggregateStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorageTransaction.java
- styx-common/src/main/java/com/spotify/styx/storage/InMemStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/Storage.java
- styx-common/src/main/java/com/spotify/styx/storage/StorageTransaction.java
- styx-common/src/main/java/com/spotify/styx/util/ShardedCounter.java
- styx-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
- styx-common/src/test/java/com/spotify/styx/util/ShardedCounterSnapshotFactoryTest.java
- styx-common/src/test/java/com/spotify/styx/util/ShardedCounterTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
Rework of #489
Remove `Resource` kind because it is not used by scheduler.
So the idea (or the way I choose to convince myself regarding resource vs. counter) is, resource is the concept we expose to users while counter is only referred internally.
`Resource` kind is not used for controlling resource usage anymore.
Unit test
> remove resource kind

- styx-api-service/pom.xml
- styx-api-service/src/main/java/com/spotify/styx/api/ServiceAccountUsageAuthorizer.java
- styx-api-service/src/test/java/com/spotify/styx/api/ServiceAccountUsageAuthorizerTest.java
Allow managed (non user created) workflow service accounts when authorizing.
Seems a fair amount of users are using GCE default SAs, app engine SAs etc for their workflows. We might want to disallow that at some point but let's not bring that into rolling out authorization.
> Authz: allow managed wf service accounts

- styx-api-service/src/main/java/com/spotify/styx/api/ServiceAccountUsageAuthorizer.java
- styx-api-service/src/test/java/com/spotify/styx/api/ServiceAccountUsageAuthorizerTest.java
Tolerate failures if not enforcing authorization
Make rolling out authorization in production less risky.
> Tolerate failures if not enforcing authorization

- styx-common/src/main/java/com/spotify/styx/monitoring/MetricsStats.java
- styx-common/src/main/java/com/spotify/styx/monitoring/NoopStats.java
- styx-common/src/main/java/com/spotify/styx/monitoring/Stats.java
- styx-common/src/test/java/com/spotify/styx/monitoring/MetricsStatsTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
After resource reference validation, record the demand of using.
To be able to understand when out of resource, roughly how bad the situation is in terms
of queuing WFI.
Unit test
> record demanded resource count

- README.md
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-cli/src/main/java/com/spotify/styx/cli/PlainCliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/PrettyCliOutput.java
- styx-cli/src/test/java/com/spotify/styx/cli/PlainCliOutputTest.java
- styx-cli/src/test/java/com/spotify/styx/cli/PrettyCliOutputTest.java
- styx-common/src/main/java/com/spotify/styx/model/WorkflowConfiguration.java
- styx-common/src/main/java/com/spotify/styx/testdata/TestData.java
- styx-common/src/main/java/com/spotify/styx/util/WorkflowValidator.java
- styx-common/src/test/java/com/spotify/styx/util/WorkflowValidatorTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/StateUtil.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/StateUtilTest.java
`runningTimeout` added to workflow configuration to customize timeout value for `running` state.
Users want to configure smaller value than the global default one.
Unit test.
> Custom running state timeout

- styx-common/src/main/java/com/spotify/styx/monitoring/MetricsStats.java
- styx-common/src/main/java/com/spotify/styx/monitoring/NoopStats.java
- styx-common/src/main/java/com/spotify/styx/monitoring/Stats.java
- styx-common/src/test/java/com/spotify/styx/monitoring/MetricsStatsTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
Emit aggregate resource demand counts instead of metering in order to produce more meaningful values.
> aggregate resource demand instead of metering

- styx-common/src/main/java/com/spotify/styx/monitoring/MetricsStats.java
- styx-common/src/main/java/com/spotify/styx/monitoring/NoopStats.java
- styx-common/src/main/java/com/spotify/styx/monitoring/Stats.java
- styx-common/src/test/java/com/spotify/styx/monitoring/MetricsStatsTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/MonitoringHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/MonitoringHandlerTest.java
remove workflow id tag from exit code meter
Stop punishing our metrics system with high-cardinality time series.
> remove workflow id tag from exit code meter

- styx-api-service/src/main/java/com/spotify/styx/api/StatusResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/StatusResourceTest.java
- styx-common/src/main/java/com/spotify/styx/api/ServiceAccountUsageAuthorizer.java
- styx-common/src/main/java/com/spotify/styx/api/TestServiceAccountUsageAuthorizationResponse.java
- styx-common/src/test/java/com/spotify/styx/api/ServiceAccountUsageAuthorizerTest.java
- styx-standalone-service/src/main/resources/styx-standalone.conf
Allow blacklisting specific undesirable principals from authorizing.
Protect against users granting authorization access to principals like e.g. a global default CI/CD service account.
Those workflows would otherwise be modifiable by (more or less) _any_ user, which is not intended.
> authz: principal blacklist

- pom.xml
Use latest version of maven-javadoc-plugin with a few tweaks.
The javadoc executable now lives in ${java.home}/bin/javadoc .
> latest version of maven-javadoc-plugin

- styx-cli/src/main/java/com/spotify/styx/cli/PlainCliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/PrettyCliOutput.java
- styx-cli/src/test/java/com/spotify/styx/cli/PlainCliOutputTest.java
- styx-cli/src/test/java/com/spotify/styx/cli/PrettyCliOutputTest.java
Original output of cli was hard to parse with shell script because of `#` separator rather than standard ` ` (space).
I also found some of the contractions in the pretty workflow show output a bit cryptic so they were extended and also left-aligned (because I find it easier to read, but I guess that's subjective).
> Some CLI workflow formatting fixes

- styx-common/src/main/java/com/spotify/styx/api/ServiceAccountUsageAuthorizer.java
- styx-common/src/test/java/com/spotify/styx/api/ServiceAccountUsageAuthorizerTest.java
Inject retry wait strategy to speed up unit tests.
No exponential delay required for unit test.
> inject retry wait strategy to speed up unit test

- styx-common/src/main/java/com/spotify/styx/api/ServiceAccountUsageAuthorizer.java
- styx-common/src/test/java/com/spotify/styx/api/ServiceAccountUsageAuthorizerTest.java
Apply blacklist and admin check before making any GCP API interaction.
There are cases that getting service account would fail due to non-exist GCP project or non-exist
service account:
```
API error: 500 Internal Server Error (Request ID: 63671a603b6d4bd5a08487c505f4731b): UncheckedExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden {   "code" : 403,   "errors" : [ {     "domain" : "global",     "message" : "Permission iam.serviceAccounts.get is required to perform this operation on service account projects/-/serviceAccounts/...",     "reason" : "forbidden"   } ],   "message" : "Permission iam.serviceAccounts.get is required to perform this operation on service account …
```
> avoid GCP API interaction if not necessary

- pom.xml
- styx-client/pom.xml
- styx-client/src/main/java/com/spotify/styx/client/auth/GoogleIdTokenAuth.java
- styx-client/src/test/java/com/spotify/styx/client/auth/GoogleIdTokenAuthTest.java
Add support to styx client for authenticating using GCE default credentials.
When using default credentials, `GoogleIdTokenAuth` will check if using GCE credentials and in that case fetch id tokens from the GCE instance metadata server.
This is so that users using GCE default credentials can use the styx client lib / cli without needing to provision service account keys.
> client: auth: GCE default credentials

- styx-common/src/main/java/com/spotify/styx/util/FutureUtil.java
- styx-common/src/test/java/com/spotify/styx/util/FutureUtilTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StateInitializingTrigger.java
- styx-scheduler-service/src/test/java/com/spotify/styx/TriggerManagerTest.java
- styx-service-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
datastore: fix readActiveStatesPartial timeouts
Instead of applying a fixed timeout to a single future at a time,
which might add up to a significantly longer execution time than
expected, enforce a "global" timeout for the `readActiveStatesPartial`
method and apply it to all the IO futures, cancelling all uncompleted
futures when timing out.
> datastore: fix readActiveStatesPartial timeouts

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/PersistentStateManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/PersistentStateManagerTest.java
Rename `QueuedStateManager` to `PersistentStateManager`.
The state manager implementation no longer has a queue, so name doesn't make any sense. The current defining property of this implementation is that it persists state in storage and performs transactional updates, so change the name to something that reflects that.
Note: Continuation of #704 which should be merged first. Change target to `master` before merging.
> Rename: QueuedStateManager -> PersistentStateManager

- styx-common/src/main/java/com/spotify/styx/util/CachedSupplier.java
- styx-common/src/test/java/com/spotify/styx/util/CachedSupplierTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/DockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/LocalDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/RoutingDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/DockerRunnerHandler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/TimeoutHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SystemTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodPollerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/RoutingDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/DockerRunnerHandlerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/TimeoutHandlerTest.java
Remove the `restore` step that block scheduler startup.
* Make `DockerRunnerHandler` poll for execution status and emit events.
* Move timeout handling out of the scheduler and into a dedicated
`TimeoutHandler` that runs last.
This allows us to remove the `restore` method and stop blocking on it
during startup as timeouts are now issued _after_ checking if the
pod is done.
> scheduler: remove the startup restore step

- .circleci/config.yml
Avoid getting OOM killed on circle-ci when compiling/running static analysis.
https://circleci.com/gh/spotify/styx/6059
https://circleci.com/gh/spotify/styx/6061
> circle: configure mvn heap size

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
* Check if pod exists before creating
* log more pod creation info
Provide more log messages that can be used to debug unexpected pod creation behavior.
> K8s: check pod exists before creating and log more

- styx-common/pom.xml
- styx-common/src/main/java/com/spotify/styx/util/CachedSupplier.java
- styx-common/src/test/java/com/spotify/styx/util/CachedSupplierTest.java
Use guava cache instead of rolling our own caching.
* Avoid having to maintain our own implementation.
* Gain useful features, like async refresh.
> Use guava cache

- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/PersistentStateManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/StateTransitionConflictException.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/PersistentStateManagerTest.java
- styx-service-common/src/main/java/com/spotify/styx/state/FanOutputHandler.java
- styx-service-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-service-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
Some fixes for https://github.com/spotify/styx/pull/714
* Throw a new specialized Exception, `StateTransitionConflictException` on state transition failure due to transaction conflict or stale events (concurrent transition conflict). 
* Swallow this exception in periodically invoked tick-style call-sites.
* Handle processing errors in the scheduler tick.
* There is too much conflict spam in the logs.
* Any failure during the scheduler tick is causing the tick duration to not be reported.
> silence state transition conflict spam + fix scheduler error handling

- styx-api-service/src/main/java/com/spotify/styx/api/WorkflowResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/BackfillResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-cli/src/main/java/com/spotify/styx/cli/CliMain.java
- styx-cli/src/test/java/com/spotify/styx/cli/CliMainTest.java
- styx-common/src/main/java/com/spotify/styx/util/WorkflowValidator.java
- styx-common/src/test/java/com/spotify/styx/util/WorkflowValidatorTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/api/SchedulerResourceTest.java
Disallow hash in component.
Avoid collisions now that we key workflows by concatenating component id and workflow id by '#'.
> validator: disallow hash in component

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
kdr: remove redundant watch reconnect
The fabric8 watcher handles reconnects on its own, so we were leaking
connections by creating a new watch on each disconnect.
> kdr: remove redundant watch reconnect

- styx-service-common/src/main/java/com/spotify/styx/util/Connections.java
datastore: disable client built-in retries
Disable retries as the datastore client (at the time of writing) has a retry bug
where it incorrectly retries ABORTED lookup operations in transactions without
restarting the transaction. This results in 3 INVALID_ARGUMENT "transaction closed" errors
that pollute our warning/error logs.
We have our own retry implementation in DatastoreStorage#storeWithRetries.
This has the downside that retryable transient RPC errors inside transactions will now
cause transactions to be rolled back and retried, which is a more expensive operation than
immediately retrying the RPC.
> datastore: disable client built-in retries

- styx-service-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-service-common/src/main/java/com/spotify/styx/storage/DatastoreStorageTransaction.java
- styx-service-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
As part of the flattening of the workflows keys to reduce transaction contention of big components this PR removes the environmental variable to conditionally write to new flat key because now we dual write by default.
Also change the read logic to only read from new keys
> Always dual write Workflows with new and old keys but only read from new

- styx-scheduler-service/src/main/java/com/spotify/styx/BackfillTriggerManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/TriggerManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
tracing: avoid large tick traces
Do not include child spans in tick parent spans to avoid those spans
growing too large (if sampled) and causing styx to run out of memory.
Additionally, reporting backends (e.g. stackdriver) typically do not
support huge spans (which is reasonable) and the tick spans
currently typically get truncated anyway.
Annotate tick spans with the number of processed entities.
> tracing: avoid large tick traces

- styx-service-common/src/main/java/com/spotify/styx/storage/DatastoreStorageTransaction.java
- styx-service-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
As part of the flattening of the workflow keys now we stop writing (and deleting) workflows with the legacy keys. We are still filtering the old keys when reading
> Remove dual writing

- .circleci/config.yml
Submit the coverage report aggregated by jacoco instead of relying on codecov.
Codecov cannot aggregate the complete inter-module coverage because jacoco strips away inter-module coverage from the per-module jacoco.xml reports. Codecov relies on and aggregates the per-module jacoco.xml reports and then ends up missing all the inter-module method traces.
> Submit jacoco aggregate

- styx-service-common/src/main/java/com/spotify/styx/api/ManagedServiceAccountKeyCredential.java
- styx-service-common/src/main/java/com/spotify/styx/api/ServiceAccountUsageAuthorizer.java
- styx-service-common/src/main/java/com/spotify/styx/api/ServiceAccounts.java
- styx-service-common/src/test/java/com/spotify/styx/api/ManagedServiceAccountKeyCredentialTest.java
- styx-service-common/src/test/java/com/spotify/styx/api/ServiceAccountUsageAuthorizerTest.java
- styx-service-common/src/test/java/com/spotify/styx/api/ServiceAccountsTest.java
Do not require having a physical service account key for the styx api and scheduler.
This will allow us to deploy styx using GCE host assigned managed service accounts instead of provisioning physical keys.
> allow using a managed service account key

- pom.xml
- styx-service-common/src/test/java/com/spotify/styx/api/GoogleIdTokenParserTest.java
- styx-service-common/src/test/java/com/spotify/styx/api/GoogleIdTokenVerifierTest.java
JWT with extra google cloud compute metadata triggers a parsing bug  in the google.http.client.lib  1.29.1.
```yaml
{
azp: 103411466401044735393,
email: some.email@project.iam.gserviceaccount.com,
email_verified: true,
exp: 1565270045,
iat: 1565266445,
iss: https://accounts.google.com,
sub: 103411466401044735393,
google: {
compute_engine: {
instance_creation_timestamp: 1556025719,
instance_id: 5853837336805153889,
instance_name: some-host,
project_id: some-project,
project_number: 213281561831,
zone: europe-west1-d
}
}
}
```
In this example everything under `google` key is the "extra" metadata and causes a problem parsing the project number as a `int` (overflows).
Here we create a Unit Test to reproduce the problem and bump the library that reverts the problematic commit that caused the …
> Fix parsing of auth tocken with google cloud compute metadata

- styx-api-service/src/main/java/com/spotify/styx/StyxApi.java
- styx-api-service/src/test/java/com/spotify/styx/api/BackfillResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/ResourceResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/StatusResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-service-common/src/main/java/com/spotify/styx/storage/AggregateStorage.java
- styx-service-common/src/main/java/com/spotify/styx/storage/BigtableStorage.java
- styx-service-common/src/test/java/com/spotify/styx/storage/BigTableStorageTest.java
- styx-service-common/src/test/java/com/spotify/styx/util/ShardedCounterSnapshotFactoryTest.java
- styx-service-common/src/test/java/com/spotify/styx/util/ShardedCounterTest.java
Use retryer lib instead.
~Depends on #779~
To simply code.
> No custom retryer in bigtable storage

- styx-api-service/src/main/java/com/spotify/styx/api/StatusResource.java
This PR addresses issues connecting to PR: https://github.com/spotify/styx/pull/774
Now the getActiveStates endpoint will use a separate thread pool instead of the main FJP and it uses the `concurrentHashMap` instead to prevent race condition.
> Use a new thread pool for get active states

- styx-api-service/src/main/java/com/spotify/styx/api/StatusResource.java
`Try.sequence` does things for us so we can limit to `IOException` only in a compact way.
> use sequence to simplify usage of Try

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/DockerRunnerId.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/DockerRunnerIdTest.java
Always use the globally configured runner when submitting.
To make `runnerId` not sticky to the cluster it used before.
> Global runner for submitting state

- styx-service-common/src/main/java/com/spotify/styx/storage/AggregateStorage.java
- styx-service-common/src/main/java/com/spotify/styx/storage/BigtableStorage.java
- styx-service-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-service-common/src/test/java/com/spotify/styx/storage/AggregateStorageTest.java
- styx-service-common/src/test/java/com/spotify/styx/storage/BigTableStorageTest.java
Use dedicated FJP for IO operation.
~Depends on #780~
Using common FJP for IO operation is not a good practice. This change should also improve performance.
> No common FJP for BigtableStorage

- styx-common/src/main/java/com/spotify/styx/model/ExecutionDescription.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandlerTest.java
- styx-service-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
When adding this feature, we forgot to persist it. Adding `runningTimeout` in persistent event
will help users understand what the timeout was when the execution happened.
> add runningTimeout to execution description

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerTest.java
missing `container.clusters.getCredentials` permission in GCP will result null cert and key and we want it to fail loudly.
> fail loudly when missing cert

- styx-client/src/main/java/com/spotify/styx/client/StyxOkHttpClient.java
- styx-client/src/main/java/com/spotify/styx/client/StyxWorkflowClient.java
- styx-client/src/test/java/com/spotify/styx/client/StyxOkHttpClientTest.java
Add a client method to get all workflows for a component.
To have a more complete API and the user will not have to do filtering per component id on their end.
Added a unit test
> Get workflows by componentId method in java client

- styx-common/src/main/java/com/spotify/styx/model/WorkflowWithState.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandlerTest.java
- styx-service-common/src/main/java/com/spotify/styx/storage/AggregateStorage.java
- styx-service-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-service-common/src/main/java/com/spotify/styx/storage/Storage.java
- styx-service-common/src/test/java/com/spotify/styx/storage/AggregateStorageTest.java
- styx-service-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
If the workflow has been disabled between retry and it is naturally triggered, we halt it.
The hypothesis is in this case users would most likely want the instance to stop.
**Note, this is a breaking change.**
> halt workflow instance if disabled and naturally triggered

- doc/api.apib
- styx-api-service/src/main/java/com/spotify/styx/api/WorkflowResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-cli-unshaded/src/main/java/com/spotify/styx/cli/CliMain.java
- styx-cli-unshaded/src/main/java/com/spotify/styx/cli/JsonCliOutput.java
- styx-cli-unshaded/src/test/java/com/spotify/styx/cli/CliMainTest.java
- styx-cli-unshaded/src/test/java/com/spotify/styx/cli/JsonCliOutputTest.java
- styx-client/src/main/java/com/spotify/styx/client/StyxOkHttpClient.java
- styx-client/src/main/java/com/spotify/styx/client/StyxWorkflowClient.java
- styx-client/src/test/java/com/spotify/styx/client/StyxOkHttpClientTest.java
With the new model, we can make one single API call to get both workflow and its state.
To save some traffic and make it more handy to script.
> new api endpoint for workflow with state

- README.md
- doc/api.apib
- pom.xml
- styx-common/pom.xml
- styx-common/src/main/java/com/spotify/styx/model/WorkflowConfiguration.java
- styx-common/src/main/java/com/spotify/styx/testdata/TestData.java
- styx-common/src/main/java/com/spotify/styx/util/BasicWorkflowValidator.java
- styx-common/src/test/java/com/spotify/styx/util/BasicWorkflowValidatorTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/TerminationHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/TerminationHandlerTest.java
Alternative of #783 
A [SpEL](https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#expressions) boolean expression.
If the expression evaluates to `false`, Styx will stop retrying and halt the workflow instance immediately. This
configuration has no impact on possible max number of tries, meaning it can only be used to halt workflow instance
earlier.
The following variables will be injected by Styx so that they can be used in the expression:
* \#exitCode: the exit code from the last execution
* \#tries: total number of tries, which equals to `1` when the first time a workflow instance gets executed and `2` when
the first retry is issued
* \#consecutiveFailures: total number of consecutive failures that is not `missing dependency`
* \#triggerType: `natural`, …
> flexible retry alt

- styx-scheduler-service/src/main/java/com/spotify/styx/BackfillTriggerManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/BackfillTriggerManagerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/TriggerManagerTest.java
If global enabled flag is false, stop triggering backfills. Scheduling is stopped effectively by sending instances back to queue.
Alternative of https://github.com/spotify/styx/pull/814
This would come handy when applying maintenance work.
Natural trigger should be OK if not beginning of an hour; backfills shouldn't be a lot; randomized delay could smear out big backlog.
> No backfill trigger and back to queue if disabled

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/DockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManagerTest.java
- styx-service-common/src/main/java/com/spotify/styx/monitoring/MetricsStats.java
- styx-service-common/src/main/java/com/spotify/styx/monitoring/NoopStats.java
- styx-service-common/src/main/java/com/spotify/styx/monitoring/Stats.java
- styx-service-common/src/test/java/com/spotify/styx/monitoring/MetricsStatsTest.java
Add a new metric to track service account cleanup rate.
We can set up an alert when the rate drops below threshold so we know service account cleanup
stops working.
> track service account cleanup rate

- styx-scheduler-service/src/main/java/com/spotify/styx/state/PersistentStateManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/PersistentStateManagerTest.java
In most if not all cases, this IAE is caused by sending event to an already finished and deleted
workflow instance, and this exception has already been logged as warning. So this PR excludes
it from error log to decrease the noise level.
> do not log IAE as error

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerTest.java
The statemanager is not bound to bound to the environment, so trying to resolve it in that way would not work.
Instead we pass along the actual instance since it's right there.
```
1) Explicit bindings are required and com.spotify.styx.state.StateManager is not explicitly bound.
while locating com.spotify.styx.state.StateManager
```
> fix error statemanager is not bound to environment

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/NoopFlyteRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/FlyteRunnerHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteAdminClientRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/NoopFlyteRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/FlyteRunnerHandlerTest.java
Make FlyteRunner.createExecution return the runnerId
Currently `FlyteRunnerHandler` emit events with  "replace-me" id but it needs to emit event with the id of the underling runner.
The configuration will contain several configurations for different runnerId (see #845) but it depends on the FlyteRunner knowing what is the runnerId and communicate that to the Handler. We don't really need to return a FlyteExecutionId so we return the runnerId as it is done in `DockerRunner`
I have included unit tests. We will verify this on stagiing environment.
> Make FlyteRunner.createExecution return the runnerId

- styx-e2e-test/src/test/resources/styx-e2e-test-scheduler.conf
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/AbstractRoutingRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/RoutingDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/RoutingFlyteRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/AbstractRoutingRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/RoutingDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/RoutingFlyteRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/FlyteRunnerHandlerTest.java
Route Flyteadmin connections depending on the runnerid.
Usually there is several environments: production and staging and with this change, 
we can configure flyteadmin connections per runner ids like this:
```
styx.flyte.admin.production.host = "flyteadmin.production.example.com"
styx.flyte.admin.production.port = 81
styx.flyte.admin.production.insecure = false
styx.flyte.admin.staging.host = "flyteadmin.staging.example.com"
styx.flyte.admin.staging.port = 81
styx.flyte.admin.staging.insecure = false
```
I have included unit tests. And we will do manual tests later. Full end to end for Flyte is coming in a different PR.
> Make FlyteRunner connect flyteadmin base on id

- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlytePhase.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteAdminClientRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlytePhaseTest.java
An undefined phase should not be handled as an error
> do not fail at undefined flyte phase

- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteAdminClientRunnerTest.java
Treat ALREADY_EXISTS exception in `createExecution` as OK
In the rare cases that we are repeating the event that leads to create the same execution twice we will get ALREADY_EXISTS. This PR catch this scenario and return as is we created the execution successfully.
There is a problem in translating styx-run-id to flyte exec name: flyte exec names are shorter. So we did a mapping that has a very low probability of generating a collisions 
([see](https://github.com/spotify/styx/blob/288995d6aad3040886fa271af78700f693df0578/styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/StyxIdToFlyteExecNameMapper.java#L37)). A flyte exec name collision means that two styx-run-id bellowing to a different workflow+parameters produce the same flyte exec name. 
So we can tray to create an …
> Treat ALREADY_EXISTS exception in createExecution as OK

- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteAdminClient.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/FlyteAdminClientTest.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/TestAdminService.java
Add `listProjects` to `FlyteAdminClient`.
This change is needed for cleaning up flyte executions whose styx executions are not active anymore.
```
We will need to retrieve all the project/domains
for every project/domain:
if execution was trigger by styx and styx workflow is no more then
terminate execution
```
I have included unit tests for propagating flyte executiions
> Add listProjects to FlyteAdminClient

- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteAdminClient.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/FlyteAdminClientTest.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/TestAdminService.java
Support Optional token and filter in FlyteAdminClient.listExecutions
Paginated request to listExecutions follow this format
```
token = null
do:
response = listExecutions(token)
token = response.token
while(token != null)
```
We need to make sure that FlyteAdminClient accepts null tokens, the ones used for the first call instead of throwing an exception
> Support Optional token and filter in FlyteAdminClient.listExecutions

- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/AbstractRunnerHandler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/FlyteRunnerHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/AbstractRunnerHandlerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/FlyteRunnerHandlerTest.java
Remove dead code trying to terminate executions on ERROR state.
Once RuneState reach ERROR it won't be active neither passed through the handlers, so any code in the Handler
for reacting to ERROR is futile and wont be ever run.
I have included unit tests
> Remove dead code trying to terminate executions

- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteAdminClient.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/FlyteAdminClientTest.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/TestAdminService.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/NoopFlyteRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/RoutingFlyteRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/FlyteRunnerHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteAdminClientRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/NoopFlyteRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/RoutingFlyteRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/FlyteRunnerHandlerTest.java
Annotate executions on creation. Executions are annotated with:
- styx workflow instance
- styx execution id
In order to know what execution we need to terminate after a user halt command, 
we need a way to tie an execution back to the originating styx workflow. 
Flyte execution annotation offers a nice way to do that.
I have included unit tests and I will test it on the staging environment once this is merged.
> Annotate Flyte executions

- styx-common/src/main/java/com/spotify/styx/util/ParameterUtil.java
- styx-common/src/test/java/com/spotify/styx/util/ParameterUtilTest.java
- styx-flyte-client/pom.xml
- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteAdminClient.java
- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteInputsUtils.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/FlyteAdminClientTest.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/FlyteInputsUtilsTest.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/TestAdminService.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteAdminClientRunnerTest.java
Passing the parameter (Aka. partition) to when creating a Flyte WF execution. It will fetch the launch plan from Flyte first to get all the default input. When it find a input parameter with name `parameter`, styx will replace this parameter with the real value from workflow instance.
> Passing the parameter to create execution

- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteAdminClient.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/AbstractRoutingRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/RoutingDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteExecutionId.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/NoopFlyteRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteAdminClientRunnerTerminateDanglingTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteExecutionIdTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/NoopFlyteRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/RoutingFlyteRunnerTest.java
Terminate dangling styx related executions. A dangling executions is one running in Flyte with styx annotation
whose RunState is not longer active in Styx.
A user could emit a halt command and force a RunState being on Error and it won't be active.
I have included unit tests. Will test in staging.
> Terminate dangling styx related executions

- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteAdminClientRunnerTerminateDanglingTest.java
Do not terminate flyte executions if they are young. 
A young Flyte executions is the one that it just started running at the time the termination thread kicks in.
So far the definition of young is 3 minutes.
This aims to reduce the probability of a race condition
> Do not terminate flyte executions if they are young

- .circleci/config.yml
Use authenticated docker hub pull.
Dockerhub will rate limit unauthenticated pull and that may impact our Circle CI build.
https://circleci.com/docs/2.0/private-images/
As long as PR build passes, this works.
> Use authenticated docker hub pull

- styx-cli/pom.xml
Exclude signatures from styx cli 
The cli depends on some signed jars, this change removes those signatures. 
styx -h  
gave:
```Error: A JNI error has occurred, please check your installation and try again Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes```
> Exclude signature files from styx cli 

- styx-e2e-test/src/test/resources/reference.conf
- styx-service-common/src/main/java/com/spotify/styx/api/AuthenticatorConfiguration.java
- styx-service-common/src/main/java/com/spotify/styx/api/AuthenticatorFactory.java
- styx-service-common/src/test/java/com/spotify/styx/api/AuthenticatorConfigurationTest.java
- styx-service-common/src/test/java/com/spotify/styx/api/AuthenticatorFactoryTest.java
- styx-standalone-service/src/main/resources/styx-standalone.conf
Add a config item to disable early caching
This early caching slows down integration test quite a bit which is
unnecessary.
This doesn't change production behaviour if left configured.
Unit test and e2e test.
> Add a config item to disable early caching

- pom.xml
Upgrade to JUnit 4.13.1 and completely remove trace of JUnit 5.
It's a security patch, and without excluding JUnit 5 things won't work. For details refer to "https:// github.com/ junit-team/ junit4/ issues/1678"
> Upgrade to JUnit 4.13.1

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/DockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/PodMutator.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodPollerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodResourceTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManagerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesPodEventTranslatorTest.java
Add pod mutator and default noop impl.
This enables injecting a meaningful pod mutator to change pod definition, such as adding resource requests/limits.
Unit test.
> Add pod mutator and default noop impl

- .circleci/config.yml
Setup portforwarding to flyteadmin in the test cluster for e2e test by using kubectl. So in the e2e test, styx just connect to flyteadmin on 127.0.0.1:8089. So there is no need to change flyte system deployment to open up the system to the internet.
For e2e with flyte component
> Port forwarding to flyteadmin for e2e test

- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/AdHocTriggeringIT.java
- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/BackfillIT.java
- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/CreateDeleteWorkflowIT.java
- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/DummyTest.java
- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/ScheduledTriggeringIT.java
- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/TestNamespacesTest.java
Get rid of deprecated import.
`assertThat` from `junit` has been deprecated for long. This PR fixes `styx-e2e-test` module.
> Get rid of deprecated import

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
Close ScheduledExecutorService before Bigtable connection among other things.
We experienced bigtable connection being closed when trying to emit event. This is due to it being closed before ScheduledExecutorService thread pool at shutdown/new deployment. Therefore we now close ScheduledExecutorService first.
> Change order of closing things

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
Increase num threads from 3 to 6 so that there is one for each scheduled tick method. The previous number made sense when we had less scheduled services. 
With too few threads they may compete to execute and cause performance problems.
> Increase num threads from 3 to 6

- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteAdminClient.java
Use grpc transparent retires for flyte admin client.
Use grpc transparent retires for flyte admin client.
As it is just a configuration change for the grpc client, no test added for it.
> Use grpc transparent retries

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/FlyteRunnerHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteAdminClientRunnerTest.java
Ignore expected exceptions and send in expected counter (instead of always accepting).
Emitting an event may fail due to for example exhausted counter capacity, another schedule instance took the transaction, or the scheduler is being shutting down. In those case, it should be throw an exception.
> Ignore expected exceptions

- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/NoopFlyteRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/RoutingFlyteRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/FlyteRunnerHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteAdminClientRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/NoopFlyteRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/RoutingFlyteRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/FlyteRunnerHandlerTest.java
Retry by next tick for execution poll error. Do nothing when execution polling failed as in real life, there should always be an execution in Flyte. We don't use the grpc retries because it would block the thread for a while.
> Retry by next tick for execution poll error

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/Fabric8KubernetesClient.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/Fabric8KubernetesClientTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodPollerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
Force delete a pod by setting grace period to `0` when calling k8s API.
Due to known bugs of k8s, which were only fixed in later version of k8s, we force delete a pod if it has been in terminating (possibly other states as well) for long (>= 30 minutes + 2 minutes).
> Force delete if pod in terminating for long

- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
Dequeue older partition of the same workflow first.
Currently dequeue order is completely shuffled without respecting partition age. This PR keeps shuffling as much as possible while prioritising older partition of the same workflow.
Unit test
> Dequeue older partition first

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
Force delete pod when `finishedAt` is not usable: not exist or could not be parsed.
There could be cases where k8s returns container status without `finishedAt` (this is confirmed) or wrong format (not seen yet), and coincidentally the same pod gets stuck in `terminating` state. Force delete when `finishedAt` is not usable will immediately delete the pod without grace period.
This PR can be treated as continuation of #911.
Unit test
> Force delete pod when finishedAt is not usable

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
Close the storage by reordering how the get register on the closer. Closer is a stack so 
being the first to register will make the last to close. 
Also increase the timeout for shutting down the threadpool of the persist manager.
Styx sometimes missed a Terminated event. Looking on one of the occurrences we found
failures to persist to bigtable after the change to datastore succeded. Ideally we would have some recovery for this missing event (or two phase commit that works for datastore and bigtable ;)).
The failure to write to bigtable happened in this case because we closed the storage (bigtable and datastore) before closing the thread pool of executors. So this PR is to fix that.
No unit test, but will try on staging
> Close storage last

- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteAdminClientRunnerTest.java
Add any trigger-specific env variables Flyte launch plan default inputs. This completes #918 
I added unit test for that.
> Propagate trigger params to flyte executions

- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteAdminClient.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/FlyteAdminClientTest.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/TestAdminService.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/LabelValue.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/NoopFlyteRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/RoutingFlyteRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/FlyteRunnerHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/LabelValueTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteAdminClientRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/NoopFlyteRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/RoutingFlyteRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandlerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/FlyteRunnerHandlerTest.java
Now we send STYX_EXECUTION_ID in labels but also send styx
variables also parts of annotations
In kubernetes world, Labels are meant for identifier info so STYX_EXECUTION_ID seems appropriate for that. 
However labels impose constrains not only on the key but also in the value. 
On the other hand. Annotations are mean to be used for user/tool specific metadata and also do not impose 
restriction on value format. So it seems appropriate to set all this STYX related variables.
> Redo labels and annotations on FlyteAdminClientRunner

- styx-api-service/src/main/java/com/spotify/styx/StyxApi.java
- styx-api-service/src/main/java/com/spotify/styx/api/WorkflowResource.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-service-common/src/main/java/com/spotify/styx/api/ActionAuthorizer.java
- styx-service-common/src/main/java/com/spotify/styx/api/WorkflowActionAuthorizer.java
- styx-service-common/src/test/java/com/spotify/styx/api/WorkflowActionAuthorizerTest.java
This pull requests adds an ActionAuthorizer class that can be used to implement an extra authorization system for destructive action perform on workflow though POST, DELETE AND PATCH api commands.
The default class provides a NOP class that does... well... nothing as expected but allow users to provide their own implementation for it.
> Adding ActionAuhoriser class

- styx-scheduler-service/src/main/java/com/spotify/styx/ServiceAccountKeyManager.java
I had a theory that the first read of the key after creating make encounter some issue but subsequent reads all worked. This is a hypothesis when experimenting with key creating and validation in my local setup as only the first reads has some chance to fail.
> Read key after creating

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManager.java
This PR changes the order when deleting keys and k8s secrets.
Before shipping #949 , we can apply this change first to prevent the situation that when Styx is shutting down key(s) have been deleted from a k8s secret but the secret hasn't been deleted.
The tradeoff here is, if the secret get deleted but no the key(s), they will be left unmanaged by Styx.
> [Hotfix] Delete k8s secret first (temporarily)

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManagerTest.java
This PR temporarily disables key deletion when the key(s) are found in k8s secret but cannot verified to exist in GCP.
This is a hotfix to work around a possible issue. **Note** that this PR should be reverted later.
Unit test
> [Hotfix] Temporarily disable key deletion

- styx-scheduler-service/src/main/java/com/spotify/styx/ServiceAccountKeyManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/ServiceAccountKeyManagerTest.java
- styx-service-common/src/main/java/com/spotify/styx/monitoring/MetricsStats.java
- styx-service-common/src/main/java/com/spotify/styx/monitoring/NoopStats.java
- styx-service-common/src/main/java/com/spotify/styx/monitoring/Stats.java
- styx-service-common/src/test/java/com/spotify/styx/monitoring/MetricsStatsTest.java
Add metrics to Styx to measure the number of service accounts keys created/deleted
> Add meter for key creation and deletion

- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteAdminClient.java
Retry up to 3 times calls to flyteadmin
No retry was configured, actually it was configured to retry 0 times, This cause that polling flyte executions could fail and a styx retry will happen.
No covered by unit test but covered by integration tests.
> Retry up to 3 times calls to flyteadmin

- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/RpcHelper.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/RpcHelperTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteAdminClientRunnerTerminateDanglingTest.java
https://github.com/flyteorg/flyteconsole/blob/2f0d88c98ac4eb9059e5a98deacdd1aef5c9d2ea/src/models/AdminEntity/AdminApiQuery.ts
The filters are not working the same way as flytectl.
I had to find some references in flyteconsole to fix them
https://github.com/flyteorg/flyteconsole/blob/2f0d88c98ac4eb9059e5a98deacdd1aef5c9d2ea/src/models/AdminEntity/AdminApiQuery.ts
The filter seperator is `+` and not `,`
instead of == or in, use the filter operation names
> fix filter according to flyteconsole usage

- pom.xml
- styx-e2e-test/flyte-test-workflow/requirements.txt
Bump logback and urlib
To fix [CVE-2021-33503](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-33503) and [CVE-2021-42550](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-42550).
Logback vulnerability is not really an issue unless an atacker could modify the logback config file. The python urlib is only used during integration testing with flyte.
Current tests suit should prove that the system keeps working
> Bump logback and urilib

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodPollerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodResourceTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManagerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesPodEventTranslatorTest.java
Adding STYX_EXECUTION_COUNTER env variable
We want to have more control over execution in the code. Also STYX_EXECUTION_COUNTER is mentioned in the docs, but wasn't implemented yet.
> add STYX_EXECUTION_COUNTER to docker env

- styx-service-common/src/main/java/com/spotify/styx/api/ServiceAccountUsageAuthorizer.java
Check role before checking administrators.
Also a minor fix to omit logging stacktrace for info level that was not covered by #999.
In most cases the principle would not be configured administrators, so the group member check would fail or return false, which is wasteful. Also the directory API call could be slow for unknown reason.
By swapping the two checks we should be able to save many unnecessary API calls.
Unit tests get this covered.
> Check role first before checking admin

- styx-service-common/src/main/java/com/spotify/styx/api/ServiceAccountUsageAuthorizer.java
- styx-service-common/src/test/java/com/spotify/styx/api/ServiceAccountUsageAuthorizerTest.java
This fixes a regression introduced by #1000.
We guard `checkRole` and only throw if `checkIsPrincipalAdmin` does not pass.
Early throw of `checkRole` will skip `checkIsPrincipalAdmin` and will make administrators not being able to do anything.
Unit tests all pass.
> Guard checkRole

- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/RpcHelper.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/RpcHelperTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteAdminClientRunnerTerminateDanglingTest.java
Use `ExecutionCreatedAt` to approximate when listing executions.
Also removed unnecessary running phase check since it is covered by the filter.
`StartedAt` is not indexed so the query is extremely slow, while `ExecutionCreatedAt` is. See https://github.com/flyteorg/flyteadmin/blob/master/pkg/repositories/models/execution.go#L29
Unit test
> Use ExecutionCreatedAt in filter

- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/BackfillIT.java
Increase the backfill timeout in end to end test to 10 minutes
End to end test fails with timeout (https://github.com/spotify/styx/pull/1007), so lets try bumping the time before digging deeper
Successful builds are the test for the end to end test
> Increase backfill test timeout

- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/AdHocTriggeringIT.java
- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/EndToEndTestBase.java
- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/ScheduledTriggeringIT.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManagerTest.java
- styx-service-common/src/main/java/com/spotify/styx/util/GcpUtil.java
- styx-service-common/src/test/java/com/spotify/styx/util/GcpUtilTest.java
Handle not enough keys from failed preconditions errors
Google now returns a different error to signal that it cannot create new keys. The code can handle both types of error now
This is the error produced
```
POST https://iam.googleapis.com/v1/projects/-/serviceAccounts/foo@bar.iam.gserviceaccount.com/keys
{
"code": 400,
"errors": [
{
"domain": "global",
"message": "Precondition check failed.",
"reason": "failedPrecondition"
}
],
"message": "Precondition check failed.",
"status": "FAILED_PRECONDITION"
}
at com.spotify.styx.docker.KubernetesGCPServiceAccountSecretManager.ensureServiceAccountKeySecret(KubernetesGCPServiceAccountSecretManager.java:128)
at com.spotify.styx.docker.KubernetesDockerRunner.lambda$ensureSecrets$0(KubernetesDockerRunner.java:263)
at …
```
> Handle not enough keys from failed preconditions errors

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/DockerRunnerHandler.java
Some of our Log Info lines are too big so this PR splits unnecessary big lines into Log.Info and Log.Debug. Also improved formatting
Creating massive log lines that are impacting disk writing.
> Reducing log sizes for INFO logs

- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/AdHocTriggeringIT.java
- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/BackfillIT.java
- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/CreateDeleteWorkflowIT.java
- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/ScheduledTriggeringIT.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
- improve the query performance of list executions by limiting the start date
- disable flyte execution E2E tests for now (will revisit in another PR)
> lookup since 24 hours, not days [disable e2e tests]

- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteInputsUtils.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/FlyteInputsUtilsTest.java
Match Styx variables and trigger parameters to flyte's inputs in camel case
Be more flexible on what we accept as flyte's inputs allows flyte's launchplans to adopt the idiomatic naming convention of their language.
> Match flyte's inputs in camel case

- doc/api.apib
- styx-api-service/src/main/java/com/spotify/styx/api/WorkflowResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-client/src/test/java/com/spotify/styx/client/StyxOkHttpClientTest.java
- styx-service-common/src/main/java/com/spotify/styx/storage/AggregateStorage.java
- styx-service-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-service-common/src/main/java/com/spotify/styx/storage/Storage.java
- styx-service-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
There is no endpoint for quickly getting all workflows enabled state. This PR adds it.
Currently you need to make one request per workflow which takes a long time. Since we are making some changes internally it would be good to store this information to be able to recover it.
I have included unit tests
> Add endpoint with enabled state

- pom.xml
- styx-flyte-client/pom.xml
Override arch to work around compiling on Apple silicon
The gRPC and protobuf deps we are using now are not compatible with Apple silicon, and upgrading those is not trivial (see https://github.com/spotify/styx/pull/1061). This introduce a workaround so that we can compile on Apple silicon.
Reference: https://github.com/trustin/os-maven-plugin#generated-properties
> Override arch to work around compiling on Apple silicon

- styx-api-service/src/main/java/com/spotify/styx/api/SchedulerProxyResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/SchedulerProxyResourceTest.java
Currently the host header is just reused from the old request, while it should be the host of styx scheduler.
> Set scheduler as host header

- styx-e2e-test/src/test/resources/styx-e2e-test-scheduler.conf
- styx-flyte-client/pom.xml
- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteAdminClient.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerTest.java
Add a deadline for grpc flyte client calls.
This change is required to avoid Styx keeping broken connections for a long time generating a thread starvation problem.
> Add deadline to flyte grpc client

- styx-client/src/main/java/com/spotify/styx/client/StyxOkHttpClient.java
Close okhttp response for requests we don't expect response body payload.
An OKHttp response must be closed (as explained [here](https://stackoverflow.com/questions/32080181/when-to-call-response-body-close)). For those requests we expect body payload, we read the body stream which results in `close` automatically, but for those we don't expect response body payload, currently we are not closing the response, which for some condition results in leaving threads hanging around. 
Existing tests.
> Close okhttp response

- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteAdminClient.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/FlyteAdminClientTest.java
You cannot set a global deadline like this. We need to set deadline for each request.
See https://github.com/grpc/grpc-java/issues/1495
> Fix set grpc deadline for calls to flyteadmin

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteAdminClientRunnerTerminateDanglingTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteAdminClientRunnerTest.java
- styx-service-common/src/main/java/com/spotify/styx/monitoring/MetricsStats.java
- styx-service-common/src/main/java/com/spotify/styx/monitoring/NoopStats.java
- styx-service-common/src/main/java/com/spotify/styx/monitoring/Stats.java
Adds a metric to track the number of dangling flyte workflows that get terminated
> Record dangling terminated flyte executions

- pom.xml
- styx-flyte-client/pom.xml
- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteAdminClient.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/FlyteAdminClientTest.java
- styx-flyte-client/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerTest.java
A user got an error on their execution where Styx failed to create execution on Flyte due to 503 errors.
This PR adds retries to retry when 5xx errors are receieved
> Retry in flyteadmin client

- styx-service-common/src/main/java/com/spotify/styx/api/Middlewares.java
- styx-service-common/src/test/java/com/spotify/styx/api/MiddlewaresTest.java
Matching headers as substring to handle cases we don't need to match full header name.
There are cases we cannot match full header name, so instead we check by substring match.
I modified unit test to cover this change.
> Lenient header matching

- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/AbstractRunnerHandler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/FlyteRunnerHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/AbstractRunnerHandlerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/FlyteRunnerHandlerTest.java
Handle `ERROR` state in `FlyteRunnerHandler`.
`ERROR` state is driven by `halt` event, and when that happens, we should terminate the execution in Flyte.
We are not doing the same treatment to `DockerRunnerHandler` because halting we have a dedicated thread reaping pods, see https://github.com/spotify/styx/blob/efaf212940316987380a4f2b5813a1687b9942fa/styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java#L537 and https://github.com/spotify/styx/blob/efaf212940316987380a4f2b5813a1687b9942fa/styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java#L449
> Handle error state

- styx-service-common/src/main/java/com/spotify/styx/api/Authenticator.java
- styx-service-common/src/main/java/com/spotify/styx/api/ServiceAccountUsageAuthorizer.java
- styx-service-common/src/test/java/com/spotify/styx/api/AuthenticatorTest.java
- styx-service-common/src/test/java/com/spotify/styx/api/ServiceAccountUsageAuthorizerTest.java
Handle GCP project not found correctly.
GCP will never return 404 in case of project not found, due to security reason. So we need to treat 403 as 404 for some case.
I also did some small refactorings along the way.
I updated existing tests to reflect this change.
> Handle GCP project not found

- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteInputsUtils.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/FlyteInputsUtilsTest.java
Add support to DURATION/INTEGER/FLOAT/MAP/COLLECTION flyte inputs.
> Support more flyte types

- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteInputsUtils.java
This PR is a refactor of #1093
> Refactor exceptions and yaml parser
