- README.md
> Document injected environment variables

- pom.xml
- styx-scheduler-service/pom.xml
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SystemTest.java
https://github.com/awaitility/awaitility
Besides being easier to read and understand, this also shaves off about 27 seconds off the build time.
> Use Awaitility for SystemTest

- styx-scheduler-service/src/main/java/com/spotify/styx/TriggerManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StateInitializingTriggerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/TriggerManagerTest.java
And don't use InMemStorage for tests
> Handle IOExceptions in TriggerManager

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodResourceTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
> Discard pod changes with exec id mismatch

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/InvalidExecutionException.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/DockerRunnerHandler.java
> Reject creating a pod if referenced secret does not exist

- styx-common/src/main/java/com/spotify/styx/state/RunState.java
- styx-common/src/main/java/com/spotify/styx/state/StateData.java
- styx-common/src/test/java/com/spotify/styx/state/RunStateTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StateInitializingTriggerTest.java
Preparation for injecting the trigger id into the k8s pod, and other upcoming features.
> Store triggerId in state

- pom.xml
- styx-api-service/pom.xml
- styx-api-service/src/main/java/com/spotify/styx/api/CliResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/CliResourceTest.java
- styx-cli/src/main/java/com/spotify/styx/cli/CliUtil.java
- styx-cli/src/main/java/com/spotify/styx/cli/Main.java
- styx-cli/src/main/java/com/spotify/styx/cli/PlainCliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/PrettyCliOutput.java
- styx-common/pom.xml
- styx-common/src/main/java/com/spotify/styx/api/cli/ActiveStatesPayload.java
- styx-common/src/main/java/com/spotify/styx/api/cli/EventsPayload.java
- styx-common/src/main/java/com/spotify/styx/state/RunState.java
- styx-common/src/main/java/com/spotify/styx/state/StateData.java
- styx-common/src/main/java/com/spotify/styx/util/Json.java
- styx-common/src/main/java/com/spotify/styx/util/ReplayEvents.java
- styx-common/src/test/java/com/spotify/styx/state/RunStateTest.java
- styx-common/src/test/java/com/spotify/styx/state/StateDataSerializationTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/TerminationHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/DockerRunnerHandlerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/PublisherHandlerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/TerminationHandlerTest.java
Merge after #31
This adds a general info messaging capability to the `StateData` and refactors the CLI to use it for displaying information about the active states.
> State Info

- styx-cli/src/main/java/com/spotify/styx/cli/PlainCliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/PrettyCliOutput.java
- styx-common/src/main/java/com/spotify/styx/state/RunState.java
- styx-common/src/test/java/com/spotify/styx/state/RunStateTest.java
> Display number of tries in cli

- pom.xml
- styx-cli/src/main/java/com/spotify/styx/cli/CliUtil.java
- styx-cli/src/main/java/com/spotify/styx/cli/PlainCliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/PrettyCliOutput.java
- styx-common/src/main/java/com/spotify/styx/model/EventSerializer.java
- styx-common/src/main/java/com/spotify/styx/model/EventVisitor.java
- styx-common/src/main/java/com/spotify/styx/model/WFIExecutionBuilder.java
- styx-common/src/main/java/com/spotify/styx/state/Message.java
- styx-common/src/main/java/com/spotify/styx/state/RunState.java
- styx-common/src/main/java/com/spotify/styx/storage/BigtableStorage.java
- styx-common/src/main/java/com/spotify/styx/util/EventUtil.java
- styx-common/src/test/java/com/spotify/styx/WorkflowInstanceEventFactory.java
- styx-common/src/test/java/com/spotify/styx/model/EventSerializerTest.java
- styx-common/src/test/java/com/spotify/styx/state/RunStateTest.java
- styx-common/src/test/java/com/spotify/styx/state/StateDataSerializationTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/api/SchedulerResourceTest.java
Also issue `runError` event in case of unknown resource.
> Add info event

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
When receiving event from k8s, log detailed pod status.
> log pod status

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
During starting up, sheduler may start reading cache before it is
populated from storage, which will lead to workflow not pairing
with resource.
Before starting scheduler and sources, read existing workflows from
storage and warm up the cache.
> warm up cache from storage

- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-cli/src/main/java/com/spotify/styx/cli/CliUtil.java
- styx-common/src/main/java/com/spotify/styx/model/EventSerializer.java
- styx-common/src/main/java/com/spotify/styx/model/data/WFIExecutionBuilder.java
- styx-common/src/main/java/com/spotify/styx/state/RunState.java
- styx-common/src/main/java/com/spotify/styx/state/TriggerSerializer.java
- styx-common/src/main/java/com/spotify/styx/state/TriggerVisitor.java
- styx-common/src/main/java/com/spotify/styx/util/TriggerUtil.java
- styx-common/src/test/java/com/spotify/styx/model/EventSerializerTest.java
- styx-common/src/test/java/com/spotify/styx/state/RunStateTest.java
- styx-common/src/test/java/com/spotify/styx/state/StateDataSerializationTest.java
- styx-common/src/test/java/com/spotify/styx/state/TriggerSerializerTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StateInitializingTrigger.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/TriggerListener.java
- styx-scheduler-service/src/main/java/com/spotify/styx/TriggerManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/api/SchedulerResource.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StateInitializingTriggerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/TriggerManagerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/api/SchedulerResourceTest.java
This PR also adds `backfillActiveStates` method to the StateManager.
> Define Trigger type for trigger events

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/MetricsStats.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/NoopStats.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/Stats.java
> Add activeStates metrics per state

- styx-common/src/main/java/com/spotify/styx/storage/AggregateStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/InMemStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/Storage.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/DockerRunnerHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/DockerRunnerHandlerTest.java
@bergman @fabriziodemaria @honnix
> Disabled pods cleanup if debug is enabled

- styx-api-service/src/main/java/com/spotify/styx/api/BackfillResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/BackfillResourceTest.java
- styx-cli/src/main/java/com/spotify/styx/cli/CliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/Main.java
- styx-cli/src/main/java/com/spotify/styx/cli/PlainCliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/PrettyCliOutput.java
- styx-common/src/main/java/com/spotify/styx/model/Backfill.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SystemTest.java
The colors for the various states look like this:
> Backfill fixes and improvements

- styx-common/src/main/java/com/spotify/styx/storage/AggregateStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/InMemStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/Storage.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
same as #56 but with config rather than regular resource
> Global resource config

- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/MeteredProxy.java
- styx-scheduler-service/src/test/java/com/spotify/styx/monitoring/MeteredProxyTest.java
> Surface exceptions through MeteredProxy

- styx-cli/src/main/java/com/spotify/styx/cli/Main.java
- styx-common/src/main/java/com/spotify/styx/serialization/Json.java
building on top of the refactor in #64
> [CLI] refactor error handling

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/TriggerManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/MetricsStats.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/NoopStats.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/Stats.java
- styx-scheduler-service/src/test/java/com/spotify/styx/TriggerManagerTest.java
To get statistics of natural triggers and possibably generate alerts
if we have been missing the value for some time.
> mark a success natural trigger

- styx-api-service/src/main/java/com/spotify/styx/StyxApi.java
- styx-api-service/src/main/java/com/spotify/styx/api/Middlewares.java
- styx-api-service/src/test/java/com/spotify/styx/api/MiddlewaresTest.java
- styx-cli/src/main/java/com/spotify/styx/cli/Main.java
- styx-common/src/main/java/com/spotify/styx/storage/AggregateStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/InMemStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/Storage.java
- styx-common/src/main/java/com/spotify/styx/util/CachedSupplier.java
- styx-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
- styx-common/src/test/java/com/spotify/styx/util/CachedSupplierTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
this will give server side a chance to reject request from certain
client version.
> validate client version

- styx-api-service/src/test/java/com/spotify/styx/api/BackfillResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-common/src/main/java/com/spotify/styx/model/DataEndpoint.java
- styx-common/src/main/java/com/spotify/styx/testdata/TestData.java
- styx-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
- styx-common/src/test/java/com/spotify/styx/storage/InMemoryStorageTest.java
- styx-local-files-source/src/test/java/com/spotify/styx/LocalFileScheduleSourceTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StateInitializingTriggerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SystemTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/DockerRunnerHandlerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandlerTest.java
This is a kludge to work around the linked [Docker bug](https://github.com/kubernetes/kubernetes/issues/41516).
> Add docker_termination_logging flag

- styx-cli/src/main/java/com/spotify/styx/cli/CliUtil.java
- styx-common/src/main/java/com/spotify/styx/model/EventVisitor.java
- styx-common/src/main/java/com/spotify/styx/model/data/WFIExecutionBuilder.java
- styx-common/src/main/java/com/spotify/styx/serialization/PersistentEvent.java
- styx-common/src/main/java/com/spotify/styx/state/RunState.java
- styx-common/src/main/java/com/spotify/styx/util/EventUtil.java
- styx-common/src/test/java/com/spotify/styx/WorkflowInstanceEventFactory.java
- styx-common/src/test/java/com/spotify/styx/serialization/PersistentEventTest.java
- styx-common/src/test/java/com/spotify/styx/util/ReplayEventsTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesPodEventTranslator.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/LocalDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/MetricsStats.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/NoopStats.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/Stats.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SystemTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesPodEventTranslatorTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/QueuedStateManagerTest.java
This is an alternative to https://github.com/spotify/styx/tree/dano/indicate-missing-exit-code
> Make exit code Optional instead of claiming 127 when exit code is missing

- styx-api-service/src/main/java/com/spotify/styx/StyxApi.java
- styx-common/src/main/java/com/spotify/styx/model/DataEndpoint.java
- styx-common/src/main/java/com/spotify/styx/util/FutureUtil.java
- styx-common/src/test/java/com/spotify/styx/serialization/PersistentEventTest.java
- styx-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
- styx-common/src/test/java/com/spotify/styx/storage/InMemoryStorageTest.java
- styx-local-files-source/src/test/java/com/spotify/styx/LocalFileScheduleSourceTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StateInitializingTrigger.java
- styx-scheduler-service/src/main/java/com/spotify/styx/TriggerListener.java
- styx-scheduler-service/src/main/java/com/spotify/styx/TriggerManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/StateManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/TriggerManagerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/api/SchedulerResourceTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodResourceTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/QueuedStateManagerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/SyncStateManager.java
Write trigger execution event before updating next trigger.
> fix trigger execution event loss

- styx-common/src/main/java/com/spotify/styx/state/RunState.java
- styx-common/src/main/java/com/spotify/styx/state/StateData.java
- styx-common/src/main/java/com/spotify/styx/util/RetryUtil.java
- styx-common/src/test/java/com/spotify/styx/state/RunStateTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/TerminationHandler.java
instead of using tries which is wrong, using failures to do backoff
> count number of failure for backoff

- styx-api-service/src/main/java/com/spotify/styx/api/BackfillResource.java
- styx-common/src/main/java/com/spotify/styx/model/Partitioning.java
- styx-common/src/main/java/com/spotify/styx/model/deprecated/Schedule.java
- styx-common/src/test/java/com/spotify/styx/serialization/JsonRoundtripTest.java
- styx-local-files-source/src/main/java/com/spotify/styx/LocalFileScheduleSource.java
- styx-local-files-source/src/test/resources/different-def.yaml
- styx-local-files-source/src/test/resources/example-defs.yaml
- styx-local-files-source/src/test/resources/simple-def.yaml
- styx-schedule-source/src/main/java/com/spotify/styx/schedule/model/deprecated/ScheduleDefinition.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StateInitializingTrigger.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/TriggerManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/api/SchedulerResource.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SystemTest.java
@rouzwawi 
Question about open source schedule definition. Should we go and break backward compatibility?
> partitioning changes to schedule

- styx-common/src/main/java/com/spotify/styx/model/data/deprecated/WorkflowInstanceExecutionData.java
- styx-common/src/main/java/com/spotify/styx/model/deprecated/Schedule.java
- styx-common/src/main/java/com/spotify/styx/model/deprecated/Workflow.java
- styx-common/src/main/java/com/spotify/styx/model/deprecated/WorkflowId.java
- styx-common/src/main/java/com/spotify/styx/model/deprecated/WorkflowInstance.java
> deprecated workflow should use deprecated schedule

- styx-cli/src/main/java/com/spotify/styx/cli/CliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/Main.java
- styx-cli/src/main/java/com/spotify/styx/cli/PlainCliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/PrettyCliOutput.java
> CLI: resource commands

- styx-api-service/src/main/java/com/spotify/styx/api/BackfillResource.java
- styx-api-service/src/main/java/com/spotify/styx/api/ResourceResource.java
- styx-api-service/src/main/java/com/spotify/styx/api/StyxConfigResource.java
- styx-api-service/src/main/java/com/spotify/styx/api/WorkflowResource.java
- styx-api-service/src/main/java/com/spotify/styx/api/deprecated/BackfillResource.java
- styx-api-service/src/main/java/com/spotify/styx/api/deprecated/WorkflowResource.java
Fix the same mistake I made when handling response.
> better way handling response

- README.md
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/DockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/DockerRunnerHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SystemTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodPollerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodResourceTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesPodEventTranslatorTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/RoutingDockerRunnerTest.java
Need this feature a lot!
I'm not sure this is an optimal approach, but seems to work. Of course, I didn't test it anyhow except unit tests, because I have no idea how to do it.
> Set `STYX_TRIGGER_ID`

- README.md
- styx-common/src/main/java/com/spotify/styx/util/TriggerUtil.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/DockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/DockerRunnerHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SystemTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/api/SchedulerResourceTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodResourceTest.java
@kanterov @rouzwawi 
Does it make sense to have trigger name as well?
> make trigger name as container env variable

- doc/api.apib
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/deprecated/WorkflowResourceTest.java
- styx-common/src/main/java/com/spotify/styx/model/WorkflowState.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
> return next_natural_triggerls

- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/MetricsStats.java
> regression

- styx-cli/src/main/java/com/spotify/styx/cli/Main.java
Factored out status code checking into a separate reusable method called `requireSuccess`. 
This could perhaps do with some more refactoring. It seems a little odd that the `send()` method interprets a 404 as an error.
> restore 404 handling, do not print stacktrace

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
not even sure of having PR for this.
> let's not be so specific

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
> Tag 'audit' for some logs

- pom.xml
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/DockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodPollerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
Also bump & add other dependencies as needed.
> fix k8s master connection leaks: bump k8s client

- styx-scheduler-service/src/main/java/com/spotify/styx/ServiceAccountKeyManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/DockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
> add key creation + allow both SA key & secret

- pom.xml
- styx-api-service/src/test/java/com/spotify/styx/api/BackfillResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/ResourceResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/deprecated/BackfillResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/deprecated/WorkflowResourceTest.java
- styx-common/pom.xml
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-common/src/main/java/com/spotify/styx/util/Connections.java
- styx-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-test/pom.xml
Latest datastore + bigtable libs + required deps
> bump gcp deps

- styx-client/src/main/java/com/spotify/styx/client/StyxApolloClient.java
https://github.com/spotify/styx/issues/164
> Fix cli host port

- pom.xml
> transitive dependency that should be excluded

- README.md
> describe both secret and service_account

- styx-common/src/main/java/com/spotify/styx/publisher/NoopPublisher.java
- styx-common/src/main/java/com/spotify/styx/publisher/Publisher.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/PublisherHandlerTest.java
> make publisher closable

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
Due to new version of fabric8, the old way catching up resource version
doesn't work now.
@rouzwawi PTAL
> handle old resource exception

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/CleanerTest.java
> remove unused field

- styx-scheduler-service/src/main/java/com/spotify/styx/BackfillTriggerManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/InstanceState.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/BackfillTriggerManagerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SystemTest.java
It seems better to let it live on its own.
@ulzha @danielnorberg  PTAL
> factor backfill triggering out side of Scheduler

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
@danielnorberg a quick fix by pushing down cleanup action
> push down cleanup in order not to delete pod when there is no execution id

- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
we need to decorate as well.
this is to fix #191 
@ulzha PTAL
> when counting currently used resources

- styx-cli/src/main/java/com/spotify/styx/cli/PrettyCliOutput.java
> align pretty with plain for workflow

- styx-local-files-source/src/test/java/com/spotify/styx/LocalFileScheduleSourceTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
Default timeout is 10 seconds. Raise timeout to 30 seconds.
Have less failures like this: https://circleci.com/gh/spotify/styx/1578
> test: raise timeout to avoid flaky test failures

- README.md
- doc/api-deprecated.apib
- doc/api.apib
> api blueprint for deprecated version

- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/TriggerManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesPodEventTranslator.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/MeteredProxy.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/MetricsStats.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/MonitoringHandler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/NoopStats.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/Stats.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/monitoring/MeteredProxyTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/monitoring/MetricsStatsTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/MonitoringHandlerTest.java
@ulzha PTAL
Please check `Stats.java` only, the rest is done by IntelliJ.
Test cases added.
> refactor method names to include a verb

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManager.java
The ongoing quest to reserve `error` for internal system errors.
> log user errors as warnings

- styx-common/src/main/java/com/spotify/styx/util/MissingRequiredPropertyException.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/SyncStateManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandlerTest.java
@ulzha PTAL
It's a little bit more complicated than just lowering down log level.
> log missing workflow as info instead of warning

- styx-client/src/main/java/com/spotify/styx/client/StyxApolloClient.java
> Longer timeout for all calls

- doc/api.apib
- styx-api-service/src/main/java/com/spotify/styx/StyxApi.java
- styx-api-service/src/main/java/com/spotify/styx/api/WorkflowResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/deprecated/WorkflowResourceTest.java
- styx-common/src/main/java/com/spotify/styx/model/Workflow.java
- styx-common/src/main/java/com/spotify/styx/model/deprecated/Workflow.java
- styx-common/src/main/java/com/spotify/styx/storage/InMemStorage.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/api/SchedulerResource.java
- styx-scheduler-service/src/test/java/com/spotify/styx/api/SchedulerResourceTest.java
- styx-standalone-service/src/main/resources/styx-standalone.conf
Implement a new API endpoint for letting users create and update workflows by uploading a json configuration payload.
> WIP: Json workflow config API endpoint

- styx-api-service/src/main/java/com/spotify/styx/api/WorkflowResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
historically this has been causing more troubles than benefit.
@ulzha PTAL
> patch at component level is gone from v3

- styx-api-service/src/main/java/com/spotify/styx/api/WorkflowResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-common/src/main/java/com/spotify/styx/api/Api.java
- styx-common/src/main/java/com/spotify/styx/model/Workflow.java
- styx-common/src/test/java/com/spotify/styx/api/ApiVersionTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SystemTest.java
> having a flag to disable update from schedule source

- styx-common/src/main/java/com/spotify/styx/util/GuardedRunnable.java
- styx-common/src/test/java/com/spotify/styx/util/GuardedRunnableTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/TriggerManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SystemTest.java
The triggering process may fail with an unchecked exception and hence it
can affect rest of the workflows in the map.
Remediation for INCIDENT-6128.
@ulzha @fabriziodemaria PTAL
> Guard triggering of each workflow

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
> TODO and stating why we do this

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
> the right way comparing doubles

- doc/api.apib
- styx-api-service/src/main/java/com/spotify/styx/api/WorkflowResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-common/src/main/java/com/spotify/styx/storage/AggregateStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/BigtableStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/InMemStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/Storage.java
- styx-common/src/test/java/com/spotify/styx/storage/BigTableStorageTest.java
by specifying start and stop, it is possible to query a given range;
this can ease the work for a certain way of doing pagination.
@axelri
> add the ability to scan instances with a range

- styx-scheduler-service/src/main/java/com/spotify/styx/InMemWorkflowCache.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/WorkflowCache.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SystemTest.java
the deletion request comes from a lower API or via polling
> Do not delete workflow if:

- .circleci/config.yml
- pom.xml
- styx-report/pom.xml
> rename the artifactId

- styx-client/src/main/java/com/spotify/styx/client/auth/GoogleIdTokenAuth.java
@rouzwawi @danielnorberg  PTAL
> I could be wrong but nobody seems using scopes

- styx-api-service/src/main/java/com/spotify/styx/api/WorkflowResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-common/src/main/java/com/spotify/styx/storage/AggregateStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/InMemStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/Storage.java
- styx-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
- styx-common/src/test/java/com/spotify/styx/storage/InMemoryStorageTest.java
Add endpoint to fetch all workflows belonging to a certain component
> Component GET endpoint

- doc/api.apib
> api doc for the new added API endpoint

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
> register active states while starting up

- styx-api-service/src/main/java/com/spotify/styx/api/SchedulerProxyResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/SchedulerProxyResourceTest.java
The apollo http client decorates the outgoing request with the auth header from the incoming request without bothering to check whether there already is a auth header. This causes nginx on the scheduler to fail the proxied request with 400 Bad Request.
> proxy: remove auth header to avoid duplicate headr

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
> another fix to cover no run state

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesPodEventTranslator.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
> delete pod without container status

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/DockerRunnerHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SystemTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/DockerRunnerHandlerTest.java
It feels more correct still act upon transiting, while the actual runner
can decide not to do anything.
@NatashaL PTAL
> bring back the action when transiting

- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/MeteredProxy.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/MetricsStats.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/NoopStats.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/Stats.java
- styx-scheduler-service/src/test/java/com/spotify/styx/monitoring/MeteredProxyTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/monitoring/MetricsStatsTest.java
* Also count failed operations
* Qualify operation `status` as either `success` or `error`
* Also emit detailed docker/k8s error meters with error status code
> storage & docker operation error metrics

- styx-common/src/main/java/com/spotify/styx/model/ExecutionDescription.java
- styx-common/src/main/java/com/spotify/styx/testdata/TestData.java
- styx-common/src/test/java/com/spotify/styx/model/data/WFIExecutionBuilderTest.java
- styx-common/src/test/java/com/spotify/styx/serialization/PersistentEventTest.java
- styx-common/src/test/java/com/spotify/styx/state/RunStateTest.java
- styx-common/src/test/java/com/spotify/styx/state/StateDataSerializationTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/DockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/DockerRunnerHandler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SystemTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodResourceTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManagerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesPodEventTranslatorTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/QueuedStateManagerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/DockerRunnerHandlerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/PublisherHandlerTest.java
> ExecutionDescription & K8sDR.RunSpec builders

- styx-api-service/src/main/java/com/spotify/styx/api/WorkflowResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-common/src/main/java/com/spotify/styx/model/WorkflowConfiguration.java
- styx-scheduler-service/src/main/java/com/spotify/styx/api/SchedulerResource.java
- styx-scheduler-service/src/test/java/com/spotify/styx/api/SchedulerResourceTest.java
- PATCH state will also update workflow configuration
- POST workflow will also update workflow state
> add commitSha to workflow configuration

- doc/api.apib
If OK I can take care of gh-pages as well.
> duplicated section

- styx-cli/src/main/java/com/spotify/styx/cli/CliMain.java
- styx-cli/src/test/java/com/spotify/styx/cli/CliMainTest.java
- styx-cli/src/test/java/com/spotify/styx/client/StyxApolloClientTest.java
- styx-cli/src/test/resources/com/spotify/styx/cli/workflows.yaml
- styx-client/src/main/java/com/spotify/styx/client/StyxApolloClient.java
- styx-common/pom.xml
- styx-common/src/main/java/com/spotify/styx/serialization/Json.java
Usage: 
**create**
```sh
styx workflow create <cid> -f workflow.yaml
cat workflow.yaml | styx workflow create <cid>
cat workflow.yaml | styx workflow create <cid> -f -
```
*workflow.yaml*: 
```yaml
id: bar
schedule: daily
service_account: foo@bar.com
docker_image: busybox
docker_args: 
- echo
- hello world
```
**delete** 
```
styx workflow delete <cid> <wfid>
```
> cli: workflow create & delete

- styx-api-service/src/main/java/com/spotify/styx/api/WorkflowResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
Append whatever jackson spits out to reason phrase. Not entirely sure
this is very readable, but currently don't have any better idea.
@NatashaL PTAL
> attach details to reason phrase

- styx-cli/src/main/java/com/spotify/styx/cli/CliMain.java
- styx-cli/src/test/java/com/spotify/styx/cli/CliMainTest.java
Before: 
`Sure you want to delete the workflow Fooin component foo? [yN]`
After: 
`Sure you want to delete the workflow Foo in component foo? [y/N] `
> clean up workflow deletion prompt

- styx-api-service/src/main/java/com/spotify/styx/api/BackfillResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/BackfillResourceTest.java
- styx-cli/src/main/java/com/spotify/styx/cli/CliMain.java
- styx-cli/src/main/java/com/spotify/styx/cli/PlainCliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/PrettyCliOutput.java
- styx-cli/src/test/java/com/spotify/styx/cli/CliMainTest.java
- styx-cli/src/test/java/com/spotify/styx/cli/PlainCliOutputTest.java
- styx-cli/src/test/java/com/spotify/styx/cli/PrettyCliOutputTest.java
- styx-client/src/main/java/com/spotify/styx/client/StyxApolloClient.java
- styx-client/src/main/java/com/spotify/styx/client/StyxBackfillClient.java
- styx-client/src/test/java/com/spotify/styx/client/StyxApolloClientTest.java
- styx-common/src/main/java/com/spotify/styx/api/BackfillPayload.java
- styx-common/src/main/java/com/spotify/styx/model/Backfill.java
- styx-common/src/main/java/com/spotify/styx/model/BackfillInput.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
Add one optional field when creating a backfill to describe the purpose of it.
> Backfill description

- doc/design-overview.md
> make it clearer about retry timeout

- pom.xml
- styx-api-service/src/test/java/com/spotify/styx/api/ApiVersionTestUtils.java
- styx-api-service/src/test/java/com/spotify/styx/api/JsonMatchers.java
- styx-cli/src/test/java/com/spotify/styx/cli/CliMainTest.java
- styx-cli/src/test/java/com/spotify/styx/cli/PlainCliOutputTest.java
- styx-cli/src/test/java/com/spotify/styx/cli/PrettyCliOutputTest.java
- styx-client/src/main/java/com/spotify/styx/client/StyxClientFactory.java
- styx-common/src/main/java/com/spotify/styx/model/ExecutionDescription.java
- styx-common/src/main/java/com/spotify/styx/model/data/WFIExecutionBuilder.java
- styx-common/src/main/java/com/spotify/styx/util/EventUtil.java
- styx-common/src/main/java/com/spotify/styx/util/FutureUtil.java
- styx-common/src/main/java/com/spotify/styx/util/GcpUtil.java
- styx-common/src/main/java/com/spotify/styx/util/ParameterUtil.java
- styx-common/src/main/java/com/spotify/styx/util/StreamUtil.java
- styx-common/src/main/java/com/spotify/styx/util/TimeUtil.java
- styx-common/src/main/java/com/spotify/styx/util/TriggerUtil.java
- styx-common/src/main/java/com/spotify/styx/util/WorkflowStateUtil.java
> errorprone static analysis

- styx-api-service/src/main/java/com/spotify/styx/StyxApi.java
- styx-api-service/src/main/java/com/spotify/styx/api/BackfillResource.java
- styx-api-service/src/main/java/com/spotify/styx/api/WorkflowResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/BackfillResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-cli/src/main/java/com/spotify/styx/cli/CliMain.java
- styx-cli/src/test/java/com/spotify/styx/cli/CliMainTest.java
- styx-common/src/main/java/com/spotify/styx/testdata/TestData.java
- styx-common/src/main/java/com/spotify/styx/util/TimeUtil.java
- styx-common/src/main/java/com/spotify/styx/util/WorkflowValidator.java
- styx-common/src/test/java/com/spotify/styx/util/WorkflowValidatorTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/api/SchedulerResource.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/api/SchedulerResourceTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandlerTest.java
* Reject creation of workflows with invalid configuration.
* Reject triggering of workflows & backfills with missing images and invalid workflow configuration.
> validate configuration & limit size

- styx-common/src/main/java/com/spotify/styx/api/Api.java
- styx-common/src/main/java/com/spotify/styx/api/Middlewares.java
- styx-common/src/test/java/com/spotify/styx/api/MiddlewaresTest.java
> log GET request as well for origin analysis

- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
not sure what would be a good value.
also make it a smaller batch.
@ulzha PTAL
> do not block for 30 seconds

- styx-api-service/src/main/java/com/spotify/styx/StyxApi.java
- styx-cli/src/main/java/com/spotify/styx/cli/CliMain.java
- styx-common/src/test/java/com/spotify/styx/serialization/JsonRoundtripTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesPodEventTranslator.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/MeteredProxy.java
not sure why they didn't show up before...
@ulzha PTAL
> now found codacy issues

- pom.xml
- styx-scheduler-service/pom.xml
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/Striping.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/QueuedStateManagerTest.java
> striped in-order event processing

- styx-scheduler-service/src/main/java/com/spotify/styx/BackfillTriggerManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/TriggerManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/MetricsStats.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/NoopStats.java
- styx-scheduler-service/src/main/java/com/spotify/styx/monitoring/Stats.java
- styx-scheduler-service/src/test/java/com/spotify/styx/BackfillTriggerManagerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/monitoring/MetricsStatsTest.java
`TriggerManager`, `BackfillTriggerManager` and `Scheduler`.
`Cleaner` is covered by instrumented `DockerRunner`.
> add histograms for important tick methods

- styx-scheduler-service/src/main/java/com/spotify/styx/TriggerManager.java
@fabriziodemaria just in case it works.
> trigger in parallel

- styx-scheduler-service/src/main/java/com/spotify/styx/api/SchedulerResource.java
- styx-scheduler-service/src/test/java/com/spotify/styx/api/SchedulerResourceTest.java
> test case for injecting timeout event

- styx-api-service/src/main/java/com/spotify/styx/api/BackfillResource.java
- styx-common/src/main/java/com/spotify/styx/storage/AggregateStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorageTransaction.java
- styx-common/src/main/java/com/spotify/styx/storage/InMemStorage.java
- styx-common/src/main/java/com/spotify/styx/storage/Storage.java
- styx-common/src/main/java/com/spotify/styx/storage/StorageTransaction.java
- styx-common/src/main/java/com/spotify/styx/util/TimeUtil.java
- styx-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
- styx-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTransactionTest.java
- styx-common/src/test/java/com/spotify/styx/storage/InMemStorageTest.java
- styx-common/src/test/java/com/spotify/styx/util/TimeUtilTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/BackfillTriggerManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/StateManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/BackfillTriggerManagerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/QueuedStateManagerTest.java
@fabriziodemaria we need to think about it.
> backfill in transaction

- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
Also change the log level to info to ease metrics collection.
> best effort when hitting rate limit

- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
Reverts spotify/styx#409
Not working well as expected. @fabriziodemaria
> Revert "best effort when hitting rate limit"

- styx-common/src/main/java/com/spotify/styx/model/data/WFIExecutionBuilder.java
- styx-common/src/test/java/com/spotify/styx/model/data/WFIExecutionBuilderTest.java
and timeout is issued
@fabriziodemaria We will end up with weird executions though.
> handling cases when trigger execution event is slow

- styx-common/src/main/java/com/spotify/styx/util/CounterCapacityException.java
- styx-common/src/main/java/com/spotify/styx/util/ShardNotFoundException.java
- styx-common/src/main/java/com/spotify/styx/util/ShardedCounter.java
- styx-common/src/test/java/com/spotify/styx/util/ShardedCounterTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
@NatashaL @ulzha @fabriziodemaria Start from this and close #408 ?
> clean up and swallow counter update exception

- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/QueuedStateManagerTest.java
> Scheduler uses strict event counter verification

- styx-common/src/main/java/com/spotify/styx/model/StyxConfig.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-common/src/main/java/com/spotify/styx/testdata/TestData.java
- styx-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/InstanceState.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/StateUtil.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/StateUtilTest.java
TODO: Add tests for `StateUtil.class`
> Sync resources at startup

- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
> fix misleading message

- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
> executing instead of triggering

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
> Better logging for resources sync

- styx-common/src/main/java/com/spotify/styx/util/CounterCapacityException.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/QueuedStateManagerTest.java
Send info event from `QueuedStateManager` where resource validation will be done in the future.
> send info event about resource limit

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/DockerRunnerHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/DockerRunnerHandlerTest.java
> increase the counter

- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
To get strongly consistent shard usage.
> Read(lookup) shards by key

- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
parallel stream pre-jdk 10 does not respect the concurrency of the underlying FJP
> use FJP directly instead of parallel stream

- styx-common/src/main/java/com/spotify/styx/util/ExceptionUtil.java
- styx-common/src/test/java/com/spotify/styx/util/ExceptionUtilTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/BackfillTriggerManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/TriggerManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/TriggerManagerTest.java
This causes problem that we are not progressing next natural trigger for
`AlreadyInitializedException`.
@ulzha PTAL
> we were catching wrong exception

- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
I tend to make default behaviour not to check counter. Those places where we require counter check should call the other method explicitly.
@fabriziodemaria PTAL and let's discuss it.
> by default do not check counter

- styx-common/src/main/java/com/spotify/styx/util/ReplayEvents.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/TransitionLogger.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/TransitionLoggerTest.java
> TransitionLogger should be a class by itself

- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
@danielnorberg Does this make sense?
> add debug log so we know when it converges

- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/TransitionLogger.java
@ulzha Without this it break a few metrics.
> change log level to info

- styx-scheduler-service/src/test/java/com/spotify/styx/SystemTest.java
This reverts commit f8fcad9c74a7c3b0ee531f479cef46403c2a993e.
@honnix
> Revert "disable known flaky tests (#442)"

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
Use the full map of wfis we already have.
> remove redundant wfi fetch

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesPodEventTranslatorTest.java
Does this make sense? Or do we really want to get latest Pod state?
> avoid reading pod again

- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
Including resource ID's in type equality check seems fragile.
> fix dequeue event type check

- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
> toSet is not ordered

- styx-client/src/main/java/com/spotify/styx/client/StyxApolloClient.java
- styx-client/src/main/java/com/spotify/styx/client/StyxWorkflowClient.java
- styx-client/src/test/java/com/spotify/styx/client/StyxApolloClientTest.java
This is to prepare for dangling workflows cleanup.
@ulzha PTAL
> being able to get all workflows

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManagerTest.java
> give more info

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
Reverts spotify/styx#466
As we discussed, we might want to consider bring it back. @danielnorberg
> Revert "remove redundant wfi fetch"

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesPodEventTranslator.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesPodEventTranslatorTest.java
> Revert "address one more corner case where exitCode lies"

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesPodEventTranslator.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesPodEventTranslatorTest.java
> address one more corner case where exitCode lies

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
Looks like this behavior was introduced in https://github.com/spotify/styx/pull/282
> fix pod creation / deletion race

- styx-api-service/src/test/java/com/spotify/styx/api/BackfillResourceTest.java
- styx-cli/src/main/java/com/spotify/styx/cli/PlainCliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/PrettyCliOutput.java
- styx-cli/src/test/java/com/spotify/styx/cli/PlainCliOutputTest.java
- styx-cli/src/test/java/com/spotify/styx/cli/PrettyCliOutputTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/BackfillTriggerManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/BackfillTriggerManagerTest.java
Fixes some reverse backfill issues in 2.0.11
> Reverse backfills fix

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
@Zatine PTAL
cc @danielnorberg
> should read container name instead of pod name

- styx-cli/src/main/java/com/spotify/styx/cli/CliMain.java
- styx-cli/src/main/java/com/spotify/styx/cli/CliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/JsonCliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/PlainCliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/PrettyCliOutput.java
- styx-cli/src/test/java/com/spotify/styx/cli/CliMainTest.java
- styx-cli/src/test/java/com/spotify/styx/cli/JsonCliOutputTest.java
- styx-cli/src/test/java/com/spotify/styx/cli/PlainCliOutputTest.java
- styx-cli/src/test/java/com/spotify/styx/cli/PrettyCliOutputTest.java
> cli: workflow list

- styx-api-service/src/main/java/com/spotify/styx/api/workflow/WorkflowInitializer.java
- styx-api-service/src/test/java/com/spotify/styx/api/workflow/WorkflowInitializerTest.java
- styx-common/src/main/java/com/spotify/styx/storage/DatastoreStorageTransaction.java
- styx-common/src/main/java/com/spotify/styx/storage/StorageTransaction.java
- styx-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTransactionTest.java
Another attempt of spotify/styx#520
> Store workflow in transaction

- pom.xml
- styx-standalone-service/pom.xml
- styx-standalone-service/src/main/java/com/spotify/styx/StyxService.java
https://github.com/census-instrumentation/opencensus-java
https://cloud.google.com/trace/
> add opencensus (stackdriver) tracing

- styx-api-service/src/main/java/com/spotify/styx/api/BackfillResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/BackfillResourceTest.java
- styx-client/src/main/java/com/spotify/styx/client/StyxApolloClient.java
- styx-client/src/main/java/com/spotify/styx/client/StyxBackfillClient.java
- styx-client/src/test/java/com/spotify/styx/client/StyxApolloClientTest.java
- styx-common/src/main/java/com/spotify/styx/model/EditableBackfillInput.java
This should keep backward compatibility.
@ulzha PTAL
> editable backfill input and transaction

- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
> resource limit before mutating state

- styx-common/src/main/java/com/spotify/styx/model/EventVisitor.java
- styx-common/src/main/java/com/spotify/styx/model/data/WFIExecutionBuilder.java
- styx-common/src/test/java/com/spotify/styx/model/data/WFIExecutionBuilderTest.java
Fix for https://github.com/spotify/styx/pull/539
> Fix replay commit sha

- styx-client/src/main/java/com/spotify/styx/client/StyxApolloClient.java
- styx-client/src/main/java/com/spotify/styx/client/StyxWorkflowClient.java
- styx-client/src/test/java/com/spotify/styx/client/StyxApolloClientTest.java
This is the equivalent to this API endpoint: https://spotify.github.io/styx/api.html#workflows-workflow-instance-get
> Add method to client to get workflow's instance

- README.md
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/DockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodPollerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodResourceTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManagerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesPodEventTranslatorTest.java
- styx-standalone-service/src/main/resources/styx-standalone.conf
@danielnorberg @ulzha PTAL
As discussed, it would be better to have a dedicated env.
> styx environment and logging format

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerTest.java
I think this might be the source of our excessive datastore reads.
> stats: cache active states

- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
> scheduler: cache resource limit lookup in tick

- styx-common/src/main/java/com/spotify/styx/model/data/WFIExecutionBuilder.java
- styx-common/src/test/java/com/spotify/styx/model/data/WFIExecutionBuilderTest.java
> make status as enum to keep them in one place

- styx-common/src/test/java/com/spotify/styx/util/GrpcContextUtilTest.java
- styx-test/src/main/java/com/spotify/styx/util/ClassEnforcer.java
- styx-test/src/test/java/com/spotify/styx/util/ClassEnforcerTest.java
Add utility in `styx-test` to help check enforcement such as non-instantiable class.
To test enforcement of best practice when designing a class.
> utility to verify class enforcement

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
Add logging to `KubernetesDockerRunner` `processPodUpdates()` and `processPodUpdate()`.
More logs!
N/A
> k8s: log pod update processing

- styx-cli/pom.xml
- styx-cli/src/main/java/com/spotify/styx/cli/JsonCliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/PlainCliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/PrettyCliOutput.java
- styx-cli/src/test/java/com/spotify/styx/cli/JsonCliOutputTest.java
- styx-cli/src/test/java/com/spotify/styx/cli/PlainCliOutputTest.java
- styx-cli/src/test/java/com/spotify/styx/cli/PrettyCliOutputTest.java
> cli: workflow: show: print env vars

- styx-cli/src/main/java/com/spotify/styx/cli/CliUtil.java
- styx-cli/src/main/java/com/spotify/styx/cli/PlainCliOutput.java
- styx-cli/src/main/java/com/spotify/styx/cli/PrettyCliOutput.java
- styx-cli/src/test/java/com/spotify/styx/cli/PlainCliOutputTest.java
- styx-cli/src/test/java/com/spotify/styx/cli/PrettyCliOutputTest.java
Show environment variables for backfill.
> cli: backfill: show env vars

- styx-common/src/main/java/com/spotify/styx/state/StateData.java
Removing an unused field that was added (by mistake?) in https://github.com/spotify/styx/pull/539.
> run state data: remove unused commitSha field

- doc/api.apib
This is event is missing `parameters`.
Fix api doc.
> fix api doc

- styx-cli/pom.xml
- styx-cli/src/main/java/com/spotify/styx/cli/CliMain.java
- styx-cli/src/test/java/com/spotify/styx/cli/CliMainTest.java
- styx-client/src/main/java/com/spotify/styx/client/FutureOkHttpClient.java
- styx-client/src/main/java/com/spotify/styx/client/StyxBackfillClient.java
- styx-client/src/main/java/com/spotify/styx/client/StyxClient.java
- styx-client/src/main/java/com/spotify/styx/client/StyxClientFactory.java
- styx-client/src/main/java/com/spotify/styx/client/StyxOkHttpClient.java
- styx-client/src/main/java/com/spotify/styx/client/StyxResourceClient.java
- styx-client/src/main/java/com/spotify/styx/client/StyxSchedulerClient.java
- styx-client/src/main/java/com/spotify/styx/client/StyxStatusClient.java
- styx-client/src/main/java/com/spotify/styx/client/StyxWorkflowClient.java
- styx-client/src/test/java/com/spotify/styx/client/FutureOkHttpClientTest.java
- styx-client/src/test/java/com/spotify/styx/client/OkHttpTestUtil.java
- styx-client/src/test/java/com/spotify/styx/client/StyxOkHttpClientTest.java
Breathing new life into #332 (and replacing #581 )
> switch out apollo styx client for okhttp

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManagerTest.java
Describe more clearly why we got permission denied when creating keys for SA.
To give a hint what is required to fix this problem.
> clearer error message

- pom.xml
Ensure that the exclusions in https://github.com/spotify/styx/pull/593 are comprehensive.
> ban codahale metrics

- styx-cli/src/main/java/com/spotify/styx/cli/CliMain.java
Trigger a completed workflow instance is not accurate.
> clearer message, maybe

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesPodEventTranslator.java
Fix npath complexity of the function.
> fix npath complexity

- .circleci/config.yml
- pom.xml
- styx-api-service/src/test/java/com/spotify/styx/api/workflow/WorkflowInitializerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerTest.java
Ensure that Styx works on the newly released Java 11.
> test java 11

- styx-common/src/main/java/com/spotify/styx/monitoring/MetricsStats.java
- styx-common/src/main/java/com/spotify/styx/monitoring/NoopStats.java
- styx-common/src/main/java/com/spotify/styx/monitoring/Stats.java
- styx-common/src/test/java/com/spotify/styx/monitoring/MetricsStatsTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/PublisherHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/PublisherHandlerTest.java
Report publishing success or failure.
We had a bad incident some time ago that publishing didn't work and Styx retried 420 times and that delayed workflow execution badly. We want to have a metric that we can monitor and take early action when it happens again.
Unit test.
> meter publishing result

- pom.xml
> use auto-matter 0.15.1

- pom.xml
To fix https://github.com/spotify/styx/network/alerts
> upgrade jackson to latest 2.9 version

- pom.xml
use release flag when compiling with jdk 9+
https://stackoverflow.com/a/43103038
> use release flag when compiling with jdk 9+

- pom.xml
As described by https://stackoverflow.com/questions/53010200/maven-surefire-could-not-find-forkedbooter-class
> Fix surefire forkedbooter issue

- styx-common/src/main/java/com/spotify/styx/api/Authenticator.java
- styx-common/src/test/java/com/spotify/styx/api/AuthenticatorTest.java
* Deny access to id tokens with no email
* Only call `serviceAccounts.get` for SA emails
> Auth fixes

- .circleci/config.yml
build using jdk11 + do not use jdk8
* Prepare for targeting Java 11.
* One less build to maintain.
> build using jdk11 + do not use jdk8

- pom.xml
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesPodEventTranslatorTest.java
Upgrade k8s client
The version we are using is quite old.
> Upgrade k8s client

- styx-api-service/src/main/java/com/spotify/styx/StyxApi.java
- styx-api-service/src/main/java/com/spotify/styx/api/ServiceAccountUsageAuthorizer.java
- styx-api-service/src/test/java/com/spotify/styx/StyxApiTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/ServiceAccountUsageAuthorizerTest.java
- styx-standalone-service/src/main/resources/styx-standalone.conf
> fix gsuite credential setup + spelling errors

- checkstyle-idea.xml
Styx version of spotify code style because legacy.
> styx intellij code style config

- styx-api-service/src/main/java/com/spotify/styx/api/ServiceAccountUsageAuthorizer.java
Log more info to get better understanding.
> log service account and principal email

- styx-api-service/src/main/java/com/spotify/styx/api/ServiceAccountUsageAuthorizer.java
- styx-api-service/src/test/java/com/spotify/styx/api/ServiceAccountUsageAuthorizerTest.java
As commented in the code, we swallow 400 as well and move on to the next group.
To not to fail too early.
> swallow 400 as well for member check

- styx-api-service/src/main/java/com/spotify/styx/api/ServiceAccountUsageAuthorizer.java
- styx-api-service/src/test/java/com/spotify/styx/api/ServiceAccountUsageAuthorizerTest.java
`policy.getBindings()` may return `null` if there is no binding.
To fix NPE.
> use empty list in case of null

- styx-api-service/src/main/java/com/spotify/styx/api/ServiceAccountUsageAuthorizer.java
> on project instead of service account

- styx-api-service/src/main/java/com/spotify/styx/api/ServiceAccountUsageAuthorizer.java
- styx-api-service/src/test/java/com/spotify/styx/api/ServiceAccountUsageAuthorizerTest.java
as described in the tittle.
Syntax fix and being neutral in the error message. We will be working on a PR to add doc link to error message.
> fix a few syntax errors and drop recommended way

- styx-api-service/src/main/java/com/spotify/styx/StyxApi.java
- styx-api-service/src/main/java/com/spotify/styx/api/ServiceAccountUsageAuthorizer.java
- styx-api-service/src/test/java/com/spotify/styx/api/ServiceAccountUsageAuthorizerTest.java
- styx-standalone-service/src/main/resources/styx-standalone.conf
A configurable message to include in 403 Forbidden responses when user requests fail authorization.
> authz: configurable message

- pom.xml
To address vulnerability warning from Github.
Changelog of this version: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9.8
> upgrade to latest jackson version

- README.md
- pom.xml
Exclude generated code in coverage report.
> coverage: exclude generated code

- styx-api-service/src/main/java/com/spotify/styx/StyxApi.java
- styx-common/src/main/java/com/spotify/styx/api/AuthenticatorConfiguration.java
- styx-common/src/main/java/com/spotify/styx/api/ServiceAccountUsageAuthorizer.java
- styx-common/src/main/java/com/spotify/styx/util/ConfigUtil.java
- styx-common/src/test/java/com/spotify/styx/api/ServiceAccountUsageAuthorizerTest.java
- styx-common/src/test/java/com/spotify/styx/util/ConfigUtilTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-standalone-service/src/main/resources/styx-standalone.conf
A configurable list of users/SAs/groups that are system administrators
and should be authorized to manipulate any workflow and use any
service account.
> authz: administrators

- styx-common/src/main/java/com/spotify/styx/api/ServiceAccountUsageAuthorizer.java
- styx-common/src/test/java/com/spotify/styx/api/ServiceAccountUsageAuthorizerTest.java
> fix authorization typo

- doc/api.apib
We forgot to put it to api doc.
> add running_timeout to api doc

- README.md
- doc/api.apib
Added documentation in the API and readme about the newly introduced Authorization functionality.
> Auth Documentation

- styx-scheduler-service/src/main/java/com/spotify/styx/state/StateUtil.java
> hotfix (should be reverted later)

- styx-cli/src/main/java/com/spotify/styx/cli/CliMain.java
- styx-cli/src/test/java/com/spotify/styx/cli/CliMainTest.java
Make `-a` and `-u` mandatory, otherwise later in the code we will throw NPE.
> required arguments

- styx-api-service/src/test/java/com/spotify/styx/api/workflow/WorkflowInitializerTest.java
This test case is not valid anymore after https://github.com/spotify/styx/pull/651
> delete invalid test case

- pom.xml
Promoting this from internal repo to open source, because it makes sense :)
> use later version of typesafe config

- pom.xml
Override foss-root which explicitly targets java 8.
> explicit maven compiler java version config

- styx-api-service/pom.xml
- styx-common/pom.xml
- styx-scheduler-service/pom.xml
add typesafe config dependency where it is used
We should declare direct dependencies on libraries that we use instead of relying on transitive dependencies.
Alternative to #674
> add config dependency where it is used

- styx-common/src/test/java/com/spotify/styx/api/ServiceAccountUsageAuthorizerTest.java
> fix merge error

- styx-client/src/main/java/com/spotify/styx/client/auth/GoogleIdTokenAuth.java
> remove duplicated scheme

- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/DockerRunnerHandler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/TerminationHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/DockerRunnerHandlerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandlerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/TerminationHandlerTest.java
Emit events with the counter of the origin run state.
Be more resilient against scheduler races.
> emit events with counter

- styx-common/src/main/java/com/spotify/styx/api/ServiceAccountUsageAuthorizer.java
- styx-common/src/test/java/com/spotify/styx/api/ServiceAccountUsageAuthorizerTest.java
Be clearer what the expected action is if the used principal is blacklisted.
> rephrase the message

- .circleci/config.yml
- pom.xml
- styx-client/pom.xml
- styx-client/src/main/java/com/spotify/styx/client/StyxClientFactory.java
- styx-client/src/main/java/com/spotify/styx/client/StyxOkHttpClient.java
- styx-client/src/main/java/com/spotify/styx/client/auth/GoogleIdTokenAuth.java
- styx-client/src/test/java/com/spotify/styx/client/auth/GoogleIdTokenAuthTest.java
* Switch to "cloud client" GoogleCredentials
* Support `ImpersonatedCredentials`
* Make it easier for services to use the styx client and manage workflows on behalf of users.
> client: configurable credentials

- styx-client/src/main/java/com/spotify/styx/client/GoogleIdTokenAuth.java
- styx-client/src/main/java/com/spotify/styx/client/StyxOkHttpClient.java
- styx-client/src/test/java/com/spotify/styx/client/GoogleIdTokenAuthTest.java
- styx-client/src/test/java/com/spotify/styx/client/StyxOkHttpClientTest.java
Make internal component private.
Internals should not be public.
> make GoogleIdTokenAuth package-private

- .circleci/config.yml
- pom.xml
- styx-client/pom.xml
- styx-client/src/main/java/com/spotify/styx/client/StyxClientFactory.java
- styx-client/src/main/java/com/spotify/styx/client/StyxOkHttpClient.java
- styx-client/src/main/java/com/spotify/styx/client/auth/GoogleIdTokenAuth.java
- styx-client/src/test/java/com/spotify/styx/client/auth/GoogleIdTokenAuthTest.java
Backport of client: configurable credentials #683
> [2.0.x] Client configurable credential

- styx-client/src/main/java/com/spotify/styx/client/GoogleIdTokenAuth.java
- styx-client/src/main/java/com/spotify/styx/client/StyxOkHttpClient.java
- styx-client/src/test/java/com/spotify/styx/client/GoogleIdTokenAuthTest.java
- styx-client/src/test/java/com/spotify/styx/client/StyxOkHttpClientTest.java
> [2.0.x] Package private auth

- styx-common/src/main/java/com/spotify/styx/util/DockerImageValidator.java
- styx-common/src/test/java/com/spotify/styx/util/DockerImageValidatorTest.java
> fix docker image digest validation

- styx-common/src/main/java/com/spotify/styx/util/FutureUtil.java
- styx-common/src/test/java/com/spotify/styx/util/FutureUtilTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/StateManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodPollerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-service-common/src/main/java/com/spotify/styx/storage/AggregateStorage.java
- styx-service-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-service-common/src/main/java/com/spotify/styx/storage/InMemStorage.java
- styx-service-common/src/main/java/com/spotify/styx/storage/Storage.java
- styx-service-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
Revert partial reads hotfix (#693)
> Revert partial reads (#693)

- styx-scheduler-service/src/main/java/com/spotify/styx/ScheduledExecutionUtil.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/StateManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/StateUtil.java
- styx-scheduler-service/src/test/java/com/spotify/styx/ScheduledExecutionUtilTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/QueuedStateManagerTest.java
- styx-service-common/src/main/java/com/spotify/styx/storage/AggregateStorage.java
- styx-service-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-service-common/src/main/java/com/spotify/styx/storage/InMemStorage.java
- styx-service-common/src/main/java/com/spotify/styx/storage/Storage.java
> Mitigate datastore contention

- pom.xml
- styx-scheduler-service/pom.xml
- styx-scheduler-service/src/main/java/com/spotify/styx/BackfillTriggerManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StateInitializingTrigger.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/TriggerListener.java
- styx-scheduler-service/src/main/java/com/spotify/styx/TriggerManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/api/SchedulerResource.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/StateManager.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/Striping.java
- styx-scheduler-service/src/test/java/com/spotify/styx/BackfillTriggerManagerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/TriggerManagerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/api/SchedulerResourceTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/QueuedStateManagerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/StripingTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandlerTest.java
Revert #704 and #705 as they are breaking production.
> Revert state manager simplification

- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/DockerRunnerHandler.java
> docker: log spec + state on run

- styx-scheduler-service/src/main/java/com/spotify/styx/state/QueuedStateManager.java
Log each instance with state and counter when the state manager ticks.
Provide more information through log messages that can be used to debug unexpected behavior.
> Log state manager tick

- styx-service-common/src/main/java/com/spotify/styx/storage/TransactionException.java
datastore: include more info in transaction error
> datastore: include more info in transaction error

- styx-service-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-service-common/src/main/java/com/spotify/styx/storage/DatastoreStorageTransaction.java
- styx-service-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
Now that we are writing workflows with the new key only and that we have cleaned the workflows using the old key we remove unnecessary code
> Clean up old style workflows keys

- styx-api-service/src/main/java/com/spotify/styx/StyxApi.java
- styx-common/src/main/java/com/spotify/styx/util/WorkflowValidator.java
- styx-common/src/test/java/com/spotify/styx/util/WorkflowValidatorTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/DockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodPollerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-standalone-service/src/main/resources/styx-standalone.conf
Only allow usage of whitelisted secrets, otherwise workflow creation/update/execution will fail.
> only allow usage of whitelisted secret

- styx-common/src/main/java/com/spotify/styx/testdata/TestData.java
- styx-common/src/main/java/com/spotify/styx/util/WorkflowValidator.java
- styx-common/src/test/java/com/spotify/styx/util/WorkflowValidatorTest.java
> Validate service account

- styx-api-service/src/main/java/com/spotify/styx/api/WorkflowResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-service-common/src/main/java/com/spotify/styx/api/Middlewares.java
Add warning logs for storage operation error. Also added test cases to cover exception branches.
To get better understanding what went wrong.
> add warning logs for storage error

- pom.xml
> remove duplicate system-rules dep

- pom.xml
Use jacoco 0.8.4 (latest)
Java 11+ support, etc.
https://github.com/jacoco/jacoco/releases/tag/v0.8.3
https://github.com/jacoco/jacoco/releases/tag/v0.8.4
> jacoco 0.8.4

- styx-api-service/src/main/java/com/spotify/styx/api/WorkflowResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
> Delete workflow in transaction

- styx-scheduler-service/src/main/java/com/spotify/styx/state/PersistentStateManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/PersistentStateManagerTest.java
scheduler: trigger in one transaction
Avoid partial failure & best-effort rollback kludge.
> scheduler: trigger in one transaction

- styx-api-service/src/main/java/com/spotify/styx/api/BackfillResource.java
create backfills in transaction
Guarantees that the workflow exists when the backfill is created.
> create backfills in transaction

- styx-scheduler-service/src/main/java/com/spotify/styx/state/PersistentStateManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/PersistentStateManagerTest.java
Ignore `CounterCapacityException` which happens often and should be treated as normal.
> CounterCapacityException is not an error in this case

- styx-scheduler-service/src/main/java/com/spotify/styx/MessageUtil.java
- styx-scheduler-service/src/main/java/com/spotify/styx/Scheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/PersistentStateManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/SchedulerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/PersistentStateManagerTest.java
* propagate CounterCapacityException 
* k8s: handle CounterCapacityException on pod events
* scheduler: handle CounterCapacityException
> Fix counter capacity spam

- pom.xml
> auto-matter 0.15.3

- pom.xml
Upgrade jackson to 2.9.9
https://nvd.nist.gov/vuln/detail/CVE-2019-12086
> CVE-2019-12086: jackson 2.9.9

- styx-scheduler-service/src/main/java/com/spotify/styx/BackfillTriggerManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/BackfillTriggerManagerTest.java
Refactor backfill trigger manager to:
* Make code easier to understand
* Give more consistent behavior when there are concurrent updates
> refactor backfill triggering

- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/AdHocTriggeringIT.java
- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/BackfillIT.java
- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/CreateDeleteWorkflowIT.java
- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/EndToEndTestBase.java
- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/ScheduledTriggeringIT.java
- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/ServiceAccountCleanupTest.java
- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/TestNamespaces.java
> generate + clean up test service accounts

- doc/api.apib
This attribute was not in API docs and it took me some time to find.
> Add reverse backfill example to API docs

- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
> system test: enable datastore retries

- pom.xml
- styx-api-service/src/test/java/com/spotify/styx/api/VersionedApiTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/api/SchedulerResourceTest.java
> run tests in parallel

- styx-cli/src/main/java/com/spotify/styx/cli/package-info.java
add bare minimum sources + javadoc to styx-cli
> fix releasing

- styx-service-common/src/main/java/com/spotify/styx/api/Authenticator.java
- styx-service-common/src/test/java/com/spotify/styx/api/AuthenticatorFactoryTest.java
- styx-service-common/src/test/java/com/spotify/styx/api/AuthenticatorTest.java
> authenticator: retry on request failure

- pom.xml
- styx-api-service/pom.xml
- styx-cli-unshaded/pom.xml
- styx-cli/pom.xml
- styx-client/pom.xml
- styx-common/pom.xml
- styx-e2e-test/pom.xml
- styx-report/pom.xml
- styx-scheduler-service/pom.xml
- styx-service-common/pom.xml
- styx-standalone-service/pom.xml
> fix coverage - include missing modules

- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/KubernetesCleanupTest.java
> retry kubernetes cleanup

- styx-common/pom.xml
- styx-common/src/main/java/com/spotify/styx/util/GoogleApiClientUtil.java
- styx-common/src/test/java/com/spotify/styx/util/GoogleApiClientUtilTest.java
- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/ServiceAccountCleanupTest.java
- styx-service-common/src/main/java/com/spotify/styx/api/Authenticator.java
> retry service account cleanup

- .circleci/config.yml
- gcloud-sdk-url.txt
- styx-api-service/src/test/java/com/spotify/styx/api/BackfillResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/ResourceResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/StatusResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-service-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
- styx-service-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTransactionTest.java
- styx-service-common/src/test/java/com/spotify/styx/util/ShardedCounterSnapshotFactoryTest.java
- styx-service-common/src/test/java/com/spotify/styx/util/ShardedCounterTest.java
- styx-test/pom.xml
- styx-test/src/main/java/com/spotify/styx/storage/DatastoreEmulator.java
- styx-test/src/test/java/com/spotify/styx/storage/DatastoreEmulatorTest.java
> Use latest datastore emulator

- doc/api.apib
- styx-api-service/bin/run-service.sh
- styx-api-service/src/main/java/com/spotify/styx/api/StatusResource.java
- styx-api-service/src/main/java/com/spotify/styx/api/util/InvalidParametersException.java
- styx-api-service/src/test/java/com/spotify/styx/api/StatusResourceTest.java
- styx-service-common/src/main/java/com/spotify/styx/storage/AggregateStorage.java
- styx-service-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-service-common/src/main/java/com/spotify/styx/storage/InMemStorage.java
- styx-service-common/src/main/java/com/spotify/styx/storage/Storage.java
- styx-service-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
- styx-service-common/src/test/java/com/spotify/styx/storage/InMemStorageTest.java
> Add filtering on the workflow id for active states endpoint

- doc/api.apib
- styx-api-service/src/main/java/com/spotify/styx/api/StatusResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/StatusResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/util/ApiTestUtil.java
- styx-common/src/main/java/com/spotify/styx/api/RunStateDataPayload.java
> Get active states for multi components endpoint

- doc/api.apib
> Update api doc for backfill create and modified timestamp

- styx-service-common/src/main/java/com/spotify/styx/api/Authenticator.java
Increase logging on Authenticator to better debug succesfull and unsuccessful validations of auth tokens
No tests as it is only increasing logging
> Increase logging on Authenticator

- pom.xml
> Bump jackson version to fix CVE-2019-12814

- pom.xml
the bug has been fixed and we don't use jdk8 anymore.
> remove todo in pom.xml

- pom.xml
Upgrade jackson to address security warning
> upgrade jackson to 2.9.9.3

- pom.xml
To address security warning Github issued.
> upgrade jackson to latest version

- styx-api-service/src/main/java/com/spotify/styx/api/StatusResource.java
This reverts commit 8fdcdc24c7877e71ed88ed2eb74aefc27117c85b.
> Revert "Use a new thread pood for active states"

- styx-api-service/src/main/java/com/spotify/styx/api/BackfillResource.java
Simplify FJP usage.
This issue https://bugs.openjdk.java.net/browse/JDK-8190974 has been resolved.
> simplify fjp usage

- styx-api-service/src/main/java/com/spotify/styx/StyxApi.java
- styx-api-service/src/main/java/com/spotify/styx/api/StatusResource.java
Here we forgot to register and close the closer.
> register and close the closer

- pom.xml
To make sure Styx can work with later version of k8s. Reference: https://stackoverflow.com/a/57718464
> upgrade fabric8 to latest version

- styx-api-service/src/main/java/com/spotify/styx/api/StatusResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/StatusResourceTest.java
In case of duplicated component, existing code would fail to merge maps due to key conflict.
> handle duplicated components

- doc/api.apib
- styx-common/src/main/java/com/spotify/styx/model/data/Execution.java
- styx-common/src/test/java/com/spotify/styx/model/data/WorkflowInstanceExecutionDataTest.java
- styx-service-common/src/main/java/com/spotify/styx/storage/WFIExecutionBuilder.java
- styx-service-common/src/test/java/com/spotify/styx/WorkflowInstanceEventFactory.java
- styx-service-common/src/test/java/com/spotify/styx/storage/WFIExecutionBuilderTest.java
Expose `runner_id` so that services could differentiate where the execution happened.
> expose runner_id

- pom.xml
> to address CVE-2019-16942

- styx-service-common/src/main/java/com/spotify/styx/api/ServiceAccountUsageAuthorizer.java
Clearer logging when auth fails.
> lower logging level, log retryable exception only

- styx-api-service/src/test/java/com/spotify/styx/api/BackfillResourceTest.java
> fix auto-merge failure

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManagerTest.java
> simplify test to make it easier to understand

- styx-service-common/src/main/java/com/spotify/styx/storage/DatastoreStorageTransaction.java
The previous change broke the agreement and that interrupted the world view of the transaction.
> Revert to transaction call

- styx-scheduler-service/src/main/java/com/spotify/styx/BackfillTriggerManager.java
> clearer it is backfill triggering

- styx-cli-unshaded/src/main/java/com/spotify/styx/cli/PlainCliOutput.java
- styx-cli-unshaded/src/main/java/com/spotify/styx/cli/PrettyCliOutput.java
- styx-cli-unshaded/src/test/java/com/spotify/styx/cli/PlainCliOutputTest.java
- styx-cli-unshaded/src/test/java/com/spotify/styx/cli/PrettyCliOutputTest.java
- styx-common/src/main/java/com/spotify/styx/model/ExecutionDescription.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandlerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/TerminationHandlerTest.java
- styx-service-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
This feature works but CLI doesn't print it.
> print retry_condition

- pom.xml
- styx-service-common/src/main/java/com/spotify/styx/api/ServiceAccountUsageAuthorizer.java
- styx-service-common/src/test/java/com/spotify/styx/api/ServiceAccountUsageAuthorizerTest.java
Upgrade crm lib revision to support requestedPolicyVersion 3.
Version 3 is required to set when requesting IAM policy with `condition` specified: https://cloud.google.com/iam/docs/policies#specifying-version
Otherwise this request simply fails and that results unexpected authorization failure.
I have updated unit tests.
Also tested in internal repo against real IAM.
> upgrade crm lib revision

- pom.xml
- styx-api-service/pom.xml
- styx-cli-unshaded/pom.xml
- styx-client/pom.xml
- styx-common/pom.xml
- styx-e2e-test/pom.xml
- styx-scheduler-service/pom.xml
- styx-service-common/pom.xml
The last big piece to upgrade.
> upgrade apollo

- README.md
Double quote retry_condition to make example work
> Double quote retry_condition

- styx-common/src/main/java/com/spotify/styx/util/BasicWorkflowValidator.java
Catch all runtime exceptions for retry condition. 
parseRaw might throw other types of exceptions so we catch all runtime exceptions to avoid having an internal server error.
> Catch all runtime exceptions for retry condition

- styx-flyte-client/pom.xml
> Manually bump to 2.1.76-SNAPSHOT

- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteAdminClient.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/FlyteAdminClientTest.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/TestAdminService.java
> Extend flyteadmin client

- styx-scheduler-service/pom.xml
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteExecution.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/test/FlyteExecutionTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/test/FlyteRunnerTest.java
> Create flyte execution

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteExecutionId.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlytePhase.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/NoopFlyteRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteAdminClientRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteExecutionIdTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlytePhaseTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/NoopFlyteRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/test/FlyteAdminClientRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/test/FlyteExecutionIdTest.java
- styx-service-common/src/main/java/com/spotify/styx/state/RunState.java
> Transition from running

- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteExecutionId.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/FlyteRunnerHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteAdminClientRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteExecutionIdTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/FlyteRunnerHandlerTest.java
> use polling to transitition to terminate

- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteAdminClientRunnerTest.java
> Propagate trigger

- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteEventTranslator.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/FlyteRunnerHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteAdminClientRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteEventTranslatorTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/FlyteRunnerHandlerTest.java
Transition from submitted state to running, terminate state.
> use polling after submitted

- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/FlyteAdminClientTest.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/TestAdminService.java
Refactor TestAdminService to be a simple in memory representation of FlyteAdmin.
Upcoming changes will pay attentions to annotations requires that we actually store data instead of returning dummy values.
> Refactor TestAdminService

- styx-common/src/main/java/com/spotify/styx/util/ParameterUtil.java
- styx-common/src/test/java/com/spotify/styx/util/ParameterUtilTest.java
- styx-flyte-client/pom.xml
- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteInputsUtils.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/FlyteInputsUtilsTest.java
> Refactor parameter to timestamp function

- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteRunner.java
This was an oversight of #868 as nothing will be terminated if we don't start the termination thread.
No unit test as it is a factory method, but will test it on staging
> Start terminate dangling flyte exec thread

- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
> Should terminate

- styx-flyte-client/src/main/proto/flyteidl/admin/schedule.proto
- styx-flyte-client/src/main/proto/flyteidl/event/event.proto
- styx-flyte-client/src/main/proto/update_protos.sh
Upgrade flyteidl to 0.18.8
This version contains the `CronSchedule` change.
> Upgrade flyteidl to 0.18.8

- pom.xml
- styx-api-service/src/main/java/com/spotify/styx/StyxApi.java
- styx-client/pom.xml
- styx-client/src/main/java/com/spotify/styx/client/GoogleIdTokenAuth.java
- styx-client/src/test/java/com/spotify/styx/client/GoogleIdTokenAuthTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-service-common/pom.xml
- styx-service-common/src/main/java/com/spotify/styx/api/ManagedServiceAccountKeyCredential.java
- styx-service-common/src/main/java/com/spotify/styx/api/ServiceAccountUsageAuthorizer.java
- styx-service-common/src/test/java/com/spotify/styx/api/ManagedServiceAccountKeyCredentialTest.java
- styx-service-common/src/test/java/com/spotify/styx/api/ServiceAccountUsageAuthorizerTest.java
> Use new IAMCredentials api

- pom.xml
> Revert "Bump junit from 4.13 to 4.13.1"

- pom.xml
Remove unneeded exclusion
This exclusion is not needed and it was due to my wrong interpretation of dep tree display by maven.
> Remove unneeded exclusion

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodResourceTest.java
Add execution id as label to have an unnormalized identifier
> Add execution id as label 

- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/EndToEndTestBase.java
- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/ScheduledTriggeringFlyteIT.java
> Minor cleanup

- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/CreateDeleteWorkflowIT.java
> Create delete workflow

- styx-api-service/src/main/java/com/spotify/styx/api/BackfillResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/BackfillResourceTest.java
- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/BackfillIT.java
add backfill test for flyte workflow
> backfill e2e test for flyte wf

- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/AdHocTriggeringIT.java
- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/EndToEndTestBase.java
Adhoc triggering for flyte workflow
Adhoc triggering for flyte workflow
> Adhoc triggering for flyte wf

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-service-common/src/main/java/com/spotify/styx/monitoring/MetricsStats.java
- styx-service-common/src/main/java/com/spotify/styx/monitoring/NoopStats.java
- styx-service-common/src/main/java/com/spotify/styx/monitoring/Stats.java
- styx-service-common/src/test/java/com/spotify/styx/monitoring/MetricsStatsTest.java
Log sumit->running latency of an execution with node name.
To collect better metric to understand which node is having trouble.
> Log latency per node

- styx-service-common/src/main/java/com/spotify/styx/monitoring/MetricsStats.java
> Fix duration

- styx-common/src/main/java/com/spotify/styx/model/ExecutionDescription.java
- styx-common/src/main/java/com/spotify/styx/model/data/Execution.java
- styx-common/src/main/java/com/spotify/styx/testdata/TestData.java
- styx-common/src/test/java/com/spotify/styx/model/data/ExecutionTest.java
- styx-common/src/test/java/com/spotify/styx/serialization/PersistentEventTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/ExecutionDescriptionHandler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/FlyteRunnerHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/FlyteRunnerHandlerTest.java
- styx-service-common/src/main/java/com/spotify/styx/storage/WFIExecutionBuilder.java
- styx-service-common/src/test/java/com/spotify/styx/WorkflowInstanceEventFactory.java
- styx-service-common/src/test/java/com/spotify/styx/storage/WFIExecutionBuilderTest.java
Expose flyte execution in Execution data
> Flyte execution id in Execution data

- styx-e2e-test/flyte-test-workflow/README.md
Workaround for evicted pod. We should have a proper solution.
> Instruction for recovering

- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteAdminClient.java
Comments for grpc transparent retry
.
.
> Add comments for previous commit

- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteAdminClient.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/NoopFlyteRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/RoutingFlyteRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/FlyteRunnerHandler.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteAdminClientRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/NoopFlyteRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/RoutingFlyteRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/handlers/FlyteRunnerHandlerTest.java
This reverts commit 852c07f57a53a07bae0a81129e191279cf35150c.
Revert unintended changes
> Revert "Use labels instead of annotations"

- README.md
Add empty line to readme to trigger the build system
> Empty line to trigger build system

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
> set keepalive container limits and requests

- styx-scheduler-service/src/main/java/com/spotify/styx/ServiceAccountKeyManager.java
> Add more logs for debugging

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManagerTest.java
Reverts spotify/styx#949
Wait until we can merge to avoid having a non deployable main branch.
> Revert "[Hotfix] Temporarily disable key deletion"

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManager.java
> Revert "[Hotfix] Delete k8s secret first (temporarily)"

- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteAdminClient.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientInterceptors.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerServiceFixture.java
- styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerTest.java
> Add client interceptors functionality

- styx-common/src/main/java/com/spotify/styx/model/WorkflowInstance.java
- styx-common/src/test/java/com/spotify/styx/model/WorkflowInstanceTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteAdminClientRunnerTest.java
> Fix terminating workflows error

- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/DockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodPollerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodResourceTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManagerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesPodEventTranslatorTest.java
> parse config env-vars and inject them to docker container

- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteAdminClient.java
- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteInputsUtils.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/FlyteAdminClientTest.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/FlyteInputsUtilsTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteAdminClientRunnerTest.java
> pass flyteExecConf inputs to execution

- pom.xml
> bump log4j to 2.17.0

- styx-common/src/main/java/com/spotify/styx/model/DeploymentSource.java
- styx-common/src/main/java/com/spotify/styx/model/WorkflowConfiguration.java
- styx-common/src/main/java/com/spotify/styx/testdata/TestData.java
- styx-common/src/test/java/com/spotify/styx/model/WorkflowConfigurationTest.java
- styx-service-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
source of the deployment points to the place where the configuration gets managed/deployed from
> store deployment source

- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteAdminClient.java
- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/GrpcClientMetadataInterceptor.java
- styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java
> pass rpc-origin in metadata

- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteRunner.java
adding the message from the cause to the CreateExecutionException, so that it's used in the event runError as well
> add cause to create execution exception msg

- styx-api-service/src/main/java/com/spotify/styx/StyxApi.java
- styx-api-service/src/main/java/com/spotify/styx/api/WorkflowResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-common/src/main/java/com/spotify/styx/model/WorkflowConfiguration.java
- styx-common/src/main/java/com/spotify/styx/testdata/TestData.java
- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/CreateDeleteWorkflowIT.java
- styx-e2e-test/src/test/java/com/spotify/styx/e2e_tests/EndToEndTestBase.java
Adding deploymentTime to WorkflowConfiguration when a Workflow is created.
It makes is easy for a user to check when a workflow was created
> Added Deployment Time

- pom.xml
Bump jackson dependencies
jackson-databind is a data-binding package for the Jackson Data Processor. jackson-databind allows a Java stack overflow exception and denial of service via a large depth of nested objects.
Bumping libraries, current test should make sure that new libraries do not break the code
> Bump jackson dependencies

- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteAdminClient.java
- styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteInputsUtils.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/FlyteAdminClientTest.java
- styx-flyte-client/src/test/java/com/spotify/styx/flyte/client/FlyteInputsUtilsTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/flyte/FlyteAdminClientRunnerTest.java
> make triggerParams optional

- styx-scheduler-service/src/main/java/com/spotify/styx/flyte/FlyteAdminClientRunner.java
to avoid situations where styx tries to terminate something that should not
> increase termination grace period

- styx-api-service/src/main/java/com/spotify/styx/api/WorkflowResource.java
- styx-api-service/src/main/java/com/spotify/styx/api/util/FilterParams.java
- styx-api-service/src/main/java/com/spotify/styx/api/util/QueryParams.java
- styx-api-service/src/main/java/com/spotify/styx/api/util/WorkflowFiltering.java
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-api-service/src/test/java/com/spotify/styx/api/util/CreateWorkflowUtil.java
- styx-api-service/src/test/java/com/spotify/styx/api/util/WorkflowFilteringTest.java
- styx-common/src/main/java/com/spotify/styx/testdata/TestData.java
> Workflow Filtering

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodPollerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerPodResourceTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesDockerRunnerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesGCPServiceAccountSecretManagerTest.java
- styx-scheduler-service/src/test/java/com/spotify/styx/docker/KubernetesPodEventTranslatorTest.java
Rename STYX_EXECUTION_TRIES variable + addressing comment from [PR](https://github.com/spotify/styx/pull/994)
> Rename STYX_EXECUTION_TRIES variable

- styx-service-common/src/main/java/com/spotify/styx/api/ServiceAccountUsageAuthorizer.java
> remove exception cause from info log

- styx-api-service/src/main/java/com/spotify/styx/api/BackfillResource.java
- styx-api-service/src/test/java/com/spotify/styx/api/BackfillResourceTest.java
- styx-cli-unshaded/src/main/java/com/spotify/styx/cli/CliMain.java
- styx-cli-unshaded/src/test/java/com/spotify/styx/cli/CliMainTest.java
- styx-client/src/main/java/com/spotify/styx/client/StyxBackfillClient.java
- styx-client/src/main/java/com/spotify/styx/client/StyxOkHttpClient.java
- styx-client/src/test/java/com/spotify/styx/client/StyxOkHttpClientTest.java
- styx-service-common/src/main/java/com/spotify/styx/storage/AggregateStorage.java
- styx-service-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
- styx-service-common/src/main/java/com/spotify/styx/storage/Storage.java
> Backfill start filter: switch from Instant.MIN default value to Instant.EPOCH. Added Unit tests.

- catalog-info.yaml
Add catalog-info.yaml to claim ownership
To make it clear about ownership of this OSS project.
NA
> Add catalog-info.yaml to claim ownership

- styx-scheduler-service/src/main/java/com/spotify/styx/state/PersistentStateManager.java
- styx-scheduler-service/src/test/java/com/spotify/styx/state/PersistentStateManagerTest.java
This PR simplifies how Inactive RunStates are handled by using Optionals instead of having Exceptions thrown all the way up the stack.
Makes it easier to understand what is actually an exception or not.
> Make RunState Optional instead of throwing Exception.

- styx-service-common/src/main/java/com/spotify/styx/storage/DatastoreStorage.java
> Get workflow with natural trigger consistently

- pom.xml
- styx-e2e-test/pom.xml
Disable IT tests.
IT has stopped working. To unblock us, we temporarily disable that.
> Temporarily disable IT tests

- pom.xml
- styx-api-service/src/test/java/com/spotify/styx/api/WorkflowResourceTest.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/handlers/StyxIdToFlyteExecNameMapper.java
- styx-service-common/src/test/java/com/spotify/styx/storage/DatastoreStorageTest.java
Bump libraries spotted by snyk
Here are the same versions as  
* https://github.com/spotify/styx/pull/1036
* https://github.com/spotify/styx/pull/1032
* https://github.com/spotify/styx/pull/1031
* https://github.com/spotify/styx/pull/1030
* https://github.com/spotify/styx/pull/1029
Plus enforcer and error prone pleasing
Prevent bit rot and address possible security issues
Same test suit
> Fix some snyk reports

- pom.xml
- styx-common/src/test/java/com/spotify/styx/util/BasicWorkflowValidatorTest.java
This PR upgrades a couple of packages affected by some vulnerabilities. 
Jackson packages depend on `org.yaml:snakeyaml` which is affected by [CVE-2022-1471](https://bitbucket.org/snakeyaml/snakeyaml/issues/561/cve-2022-1471-vulnerability-in), while `spring-expression` package is affected by [CVE-2023-20863](https://spring.io/security/cve-2023-20863). The packages this PR upgrades to have these vulnerabilities fixed.
There is a side effect: in [spring-framework `v5.3.27`](https://github.com/spring-projects/spring-framework/releases/tag/v5.3.27) they also introduced a [SpEL expression length limit](https://github.com/spring-projects/spring-framework/commit/ebc82654282bda547fbc20a9749ab1bda886a46f#diff-a3f31c4564185f813789660da1037022e2100ce097e25940a1a2d2ff14d6b2e0R100) of 10000 …
> chore: upgrading vulnerable packages

- styx-scheduler-service/src/main/java/com/spotify/styx/docker/KubernetesDockerRunner.java
- styx-scheduler-service/src/main/java/com/spotify/styx/state/PersistentStateManager.java
- styx-service-common/src/main/java/com/spotify/styx/util/ShardedCounter.java
This PR tries to reduce the INFO logs. This PR reduces the logs x4 times  lower.
> Reduce info logs
